### ISSUE TITLE
Error compile on FreeBSD 9.0 

### ISSUE THREAD

**Issue by exdeniz** [node-ffi/node-ffi#130]
```
-
`--# npm install ffi
npm http GET https://registry.npmjs.org/ffi
npm http 304 https://registry.npmjs.org/ffi
npm http GET https://registry.npmjs.org/ref-struct
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ref
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/ref-struct
npm http 304 https://registry.npmjs.org/bindings

> ref@0.1.3 install /root/node_modules/ffi/node_modules/ref
> node-gyp rebuild

gmake: п▓я┘п╬пЄ п╡ п╨п╟я┌п╟п╩п╬пЁ `/root/node_modules/ffi/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
gmake: п▓я▀я┘п╬пЄ п╦пЇ п╨п╟я┌п╟п╩п╬пЁп╟ `/root/node_modules/ffi/node_modules/ref/build'

> ffi@1.2.5 install /root/node_modules/ffi
> node-gyp rebuild

gmake: п▓я┘п╬пЄ п╡ п╨п╟я┌п╟п╩п╬пЁ `/root/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
../deps/libffi/src/x86/sysv.S:369:2: error: #error missing .ascii/.string
gmake: *** [Release/obj.target/ffi/deps/libffi/src/x86/sysv.o] п·я┬п╦п╠п╨п╟ 1
gmake: п▓я▀я┘п╬пЄ п╦пЇ п╨п╟я┌п╟п╩п╬пЁп╟ `/root/node_modules/ffi/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System FreeBSD 9.0-RELEASE
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/ffi
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by unbornchikken** [comment]
I don't understand error messages in Klingon, like "п▓я▀я┘п╬пЄ п╦пЇ п╨п╟я┌п╟п╩п╬пЁп╟". Please open up this issue again if you're having this still on a more recent version of this library and tools.
