### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by Clorr** [node-ffi/node-ffi#134]
I'm trying to run an example of node-ffi, but it crashes with the following error

```
Error: Could not locate the bindings file. Tried:
 - C:\mydir\node_modules\node-ffi\build\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\build\Debug\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\build\Release\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\out\Debug\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\Debug\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\out\Release\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\Release\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\build\default\ffi_bindings.node
 - C:\mydir\node_modules\node-ffi\compiled\0.6.6\win32\ia32\ffi_bindings.node
    at bindings (C:\mydir\node_modules\node-ffi\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\mydir\node_modules\node-ffi\lib\ffi.js:3:34)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (C:\mydir\release\node\dll\call.js:1:73)
    at Module._compile (module.js:432:26)
```

Maybe I missed something ?

**Comment by softtryme** [comment]
hello world
