### ISSUE TITLE
"%1 is not a valid Win32 application" on Windows 7 x64 with Nodejs 32-bit

### ISSUE THREAD

**Issue by bjacksoneze** [node-ffi/node-ffi#168]
Whenever I try to require ffi, I get this error:

``` bjackson@DW1-BJACKSON
$ node test.js

d:\mocks\node_modules\ffi\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: %1 is not a valid Win32 application.
d:\mocks\node_modules\ffi\node_modules\ref\build\Release\binding.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (d:\mocks\node_modules\ffi\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (d:\mocks\node_modules\ffi\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

It fails at the require step.

**Comment by HeathNaylor** [comment]
I have node 32 bit installed and get this error.

**Comment by soua-hamza** [comment]
hi I have 64 bit node and i have this error haw to fix it pls?

**Comment by soua-hamza** [comment]
my DLL is 64bit my node is 64 bit and windows 7 64 bits and i have this problem

**Comment by afroewis** [comment]
In case someone has the same problem: I also had this error. After 8 hours of trying different things without any success, I installed 32-bit node. It solved my problem.

**Comment by ykhilaji** [comment]
Hi afroewis , 

I have the same problem as you, can you show me your package.json, is how to use the DLL 32 with a 64bit node under Windows 7 64bit
thank you
