### ISSUE TITLE
"Failed to load c++ bson extension, using pure JS version" on v0.11.14 Node

### ISSUE THREAD

**Issue by windwaterbo** [node-ffi/node-ffi#177]
I upgrade node version to v0.11.14 recently. I can't use ffi to run my project . Do you think about updating it? 
```javascript
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
Failed to load c++ bson extension, using pure JS version
G:\Node\foobar\node_modules\ffi\node_modules\bindings\bindings.js
:83
        throw e
              ^
Error: The specified procedure could not be found.
g:\Node\foobar\node_modules\ffi\node_modules\ref\build\Release\bi
nding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (G:\Node\foobar\node_modules\ffi\node_modules\bin
dings\bindings.js:76:44)
    at Object.<anonymous> (G:\Node\foobar\node_modules\ffi\node_m
odules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by LinusU** [comment]
Some upgrades of node is not ABI compatible and thus require a rebuild of native modules. Could you try `npm rebuild`?

**Comment by TooTallNate** [comment]
Closing in favor of #187.
