### ISSUE TITLE
Dynamic Symbol Retrieval Error:

### ISSUE THREAD

**Issue by swaroopeshwar** [node-ffi/node-ffi#180]
i want call the "isScanDeviceAvailable" function. 

``` js
var ffi = require('ffi');
var kernel3 =ffi.Library('C:\\ThickClientTemp\\dll\\32\\TwainScaner.dll', {'isScanDeviceAvailable': [ 'int', [ 'String','boolean'] ]});
kernel3.isScanDeviceAvailable();
```

But i got the below error 

```
C:\Users\swaroopeshwar\Desktop\node js\node_modules\ffi\lib\dynamic_library.js:7
4
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: "C:\ThickClientTemp\dll\32\TwainScaner.dll": The s
pecified module could not be found.
    at new DynamicLibrary (C:\Users\swaroopeshwar\Desktop\node js\node_modules\f
fi\lib\dynamic_library.js:74:11)
    at Object.Library (C:\Users\swaroopeshwar\Desktop\node js\node_modules\ffi\l
ib\library.js:45:12)
    at Object.<anonymous> (C:\Users\swaroopeshwar\Desktop\node js\11.js:9:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

How to slove it.

**Comment by wuhao2004** [comment]
I have this problem too. 
```javascript
 if (match = err.match(/^(([^ \t()])+\.so([^ \t:()])*):([ \t])*invalid ELF header$/)) {
      var content = read(match[1], 'ascii')
      // try to find a GROUP ( ... ) command
      if (match = content.match(/GROUP *\( *(([^ )])+)/)){
        return DynamicLibrary.call(this, match[1], mode)
      }
    }
    throw new Error('Dynamic Linking Error: ' + err)
```
if i need change this code ?

**Comment by rodrigopandini** [comment]
I think that you don't need pass the ".dll" extension.
Try pass only the name of the file "C:\ThickClientTemp\dll\32\TwainScaner".
You can also check if the `os` and `arch` is valid:
Try the code bellow:

```js
var filePath = "C:\ThickClientTemp";

// check the os and arch
if ((os.platform() === "win32") || (os.platform() === "win64")) {
  if (os.arch() === "ia32") {
    filePath = path.join(filePath , "dll", "32", "TwainScaner");
  } else if (os.arch() === "x64") {
    filePath = path.join(filePath , "dll", "64", "TwainScaner");
  }
} else {
  throw new Error("OS not supported!");
}

// "binding" with dll functions
var lib = ffi.Library(filePath, {
  "isScanDeviceAvailable": ["int", ["string", "boolean"]]
});
```
