### ISSUE TITLE
Cannot make work ffi on ATMEL SAMA5D3

### ISSUE THREAD

**Issue by cheyman** [node-ffi/node-ffi#182]
Hello, 
I am very interesting in using nodejs and ffi as the main application framework on embedded target ATMEL's SAMA5D3 processor on the SAMA5D3_Xplained board.

I thus cross-compiled and customized a linux distribution using buildroot 2014-11 in order to use nodejs and ffi.

Buildroot customization for nodejs and addons is : 
![image](https://cloud.githubusercontent.com/assets/4942619/5595293/61d800ce-926f-11e4-9304-d0189b0f257a.png)

When I try to load ffi module on the embedded target, I get the following error : 
$ nano test-ffi.js
GNU nano 2.3.6             File: test-ffi.js

var ffi = require ('/usr/lib/node_modules/ffi');

                                [ Read 1 line ]

$ node test-ffi.js

/usr/lib/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
          ^
Error: Dynamic Symbol Retrieval Error: Unable to resolve symbol
    at DynamicLibrary.get (/usr/lib/node_modules/ffi/lib/dynamic_library.js:112:11)
    at Object.<anonymous> (/usr/lib/node_modules/ffi/lib/errno.js:27:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/ffi/lib/ffi.js:83:17)
    at Module._compile (module.js:456:26)
$ node --version
v0.10.33
$ uname -a
Linux buildroot 3.15.0 #1 Wed Dec 10 14:36:01 CET 2014 armv7l GNU/Linux'

Please any idea about this problem ? Any solution ?

Regards,
Cedric

**Comment by luan007** [comment]
Same problem when trying to use w/ buildroot on ARM board,

``` javascript
var ffi = require("ffi");
```

Prints:

``` 

  ffi:DynamicLibrary new DynamicLibrary() +0ms undefined undefined
  ffi:DynamicLibrary dlsym() +21ms errno
  ffi:DynamicLibrary dlerror() +5ms



Error: Dynamic Symbol Retrieval Error: Unable to resolve symbol
    at DynamicLibrary.get (/node_modules/ffi/lib/dynamic_library.js:112:11)
    at Object.<anonymous> (/node_modules/ffi/lib/errno.js:27:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/node_modules/ffi/lib/ffi.js:83:17)
    at Module._compile (module.js:456:26)

```


Would like to know if it's a problem about buildroot itself

:zap: 

Thanks

**Comment by luan007** [comment]
I've found a workaround, might be helpful:
adding default path for libc solves the prob,

``` javascript
function DynamicLibrary (path, mode) {
  if (!(this instanceof DynamicLibrary)) {
    return new DynamicLibrary(path, mode)
  }
  //add following
  path = path || "/lib/libuClibc-0.9.33.2.so"; //or /lib/libc.so.0
...
```
there might be some issue for OS/ffi to find the right libC (default one),
any follow up would be greatly helpful!

Thanks

**Comment by unbornchikken** [comment]
If you load a library then ffi (dlopen actually) will search for it in PATH. You can change the PATH variable before loading node, or you can go by setting full path of the library. May I take a look at `test-ffi.js`?

**Comment by luan007** [comment]
Great! Will give a try

**Comment by unbornchikken** [comment]
I've realised that youre using posix there, so I guess the library's path should be added to LD_LIBRARY_PATH variable instead. Please try both.
