### ISSUE TITLE
Dll pathname with non-ascii characters

### ISSUE THREAD

**Issue by datoda** [node-ffi/node-ffi#183]
Hi, I get the following error when the pathname of the dll I am loading with ffi has non-ascii characters in it: 

    $ node idevice_id_vs.js
    
    c:\Users\datod_000\dev\idevice_wi_release-τªÅΘ£╕\node_modules\ffi\lib\dynamic_library.js:74
        throw new Error('Dynamic Linking Error: ' + err)
                ^
    Error: Dynamic Linking Error: "c:\Users\datod_000\dev\idevice_wi_release-τªÅΘ£╕\libwi.dll": The specified module could not be found.
        at new DynamicLibrary (c:\Users\datod_000\dev\idevice_wi_release-τªÅΘ£╕\node_modules\ffi\lib\dynamic_library.js:74:11)
        at Object.Library (c:\Users\datod_000\dev\idevice_wi_release-τªÅΘ£╕\node_modules\ffi\lib\library.js:45:12)
        at Object.<anonymous> (c:\Users\datod_000\dev\idevice_wi_release-τªÅΘ£╕\idevice_id_vs.js:13:28)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3

In case you are curious, the pathname is actually C:\Users\datod_000\dev\idevice_wi_release-福霸\libwi.dll (chinese). If I renamed the dll pathname to all ascii characters, then ffi loads the library just fine.

Is there a way to make ffi handle pathnames with non-ascii characters? Thanks.

**Comment by unbornchikken** [comment]
Sorry, unicode characters is not yet supported. We're waiting for this https://github.com/dlfcn-win32/dlfcn-win32/pull/20 to get merged. After we can integrate this to ffi.

**Comment by unbornchikken** [comment]
I started to investigate it there: https://github.com/node-ffi/node-ffi/pull/225

**Comment by mcnameej** [comment]
This should be fixed in node-ffi 2.0.0 (change included in PR #226).
