### ISSUE TITLE
Fails to build with io.js 1.0.3

### ISSUE THREAD

**Issue by unbornchikken** [node-ffi/node-ffi#184]
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory `/home/gabor/git/NOOOCL/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gabor/git/NOOOCL/node_modules/ffi
gyp ERR! node -v v1.0.3
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v1.0.3
npm ERR! npm  v2.2.0
npm ERR! code ELIFECYCLE

**Comment by unbornchikken** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by rodrigopandini** [comment]
+1

iojs -v: 1.1.0
win7 32bits

```sh

gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Usuario\Documents\test\node_modules\ffi
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\iojs\\node.exe" "c:\\Program Files (x86)\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ffi"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.
```

**Comment by paulcbetts** [comment]
If this helps, here's a real stack (This is from Atom Shell on Chrome 41, so similar to io.js 1.1.0): 

```
C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi>node "C:\Users\Paul\code\tinyspeck\slack-winssb\build\node_modules\npm\bin\node-g
yp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dlfcn.c
  dlfcn.vcxproj -> C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\Release\\dlfcn.lib
  Building assembly file C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  ffi.vcxproj -> C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\Release\\libffi.lib
  pthread.c
  pthread.vcxproj -> C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\Release\\pthread.lib
  ffi.cc
  callback_info.cc
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(57): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(57): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(58): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(58): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(59): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(59): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(57): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(57): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(60): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(58): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(60): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(58): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(64): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(59): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(64): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(59): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(94): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\callback_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(60): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(94): error C2143: syntax error : missing ',' before '&' (..\src\callba
ck_info.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(60): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(64): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(64): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(94): error C4430: missing type specifier - int assumed. Note: C++ does
 not support default-int (..\src\ffi.cc) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\paul\code\tinyspeck\slack-winssb\node_modules\ffi\src\ffi.h(94): error C2143: syntax error : missing ',' before '&' (..\src\ffi.cc
) [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
..\src\callback_info.cc(24): error C2039: 'Dispose' : is not a member of 'v8::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>'
[C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\callback_info.cc(25): error C2039: 'Clear' : is not a member of 'v8::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>' [C
:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\ffi.cc(19): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Use
rs\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(879) : see declaration of 'v8::HandleScope::HandleScope'
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(863) : see declaration of 'v8::HandleScope'
..\src\callback_info.cc(35): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScop
e' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(879) : see declaration of 'v8::HandleScope::HandleScope'
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(863) : see declaration of 'v8::HandleScope'
..\src\ffi.cc(21): error C2882: 'Buffer' : illegal use of namespace identifier in expression [C:\Users\Paul\code\tinyspeck\slack-winssb\nod
e_modules\ffi\build\ffi_bindings.vcxproj]
..\src\callback_info.cc(47): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\f
fi\build\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(1890) : see declaration of 'v8::String'
..\src\ffi.cc(21): error C2065: 'buf' : undeclared identifier [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_binding
s.vcxproj]
..\src\callback_info.cc(46): error C3861: 'ThrowException': identifier not found [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ff
i\build\ffi_bindings.vcxproj]
..\src\ffi.cc(22): error C2039: 'Close' : is not a member of 'v8::HandleScope' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\
build\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(863) : see declaration of 'v8::HandleScope'
..\src\callback_info.cc(47): error C3861: 'New': identifier not found [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi
_bindings.vcxproj]
..\src\ffi.cc(22): error C2065: 'buf' : undeclared identifier [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_binding
s.vcxproj]
..\src\callback_info.cc(51): error C2819: type 'v8::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>' does not have an overloade
d member 'operator ->' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          with
          [
              T=v8::Function
          ]
          did you intend to use '.' instead?
..\src\ffi.cc(22): error C2227: left of '->handle_' must point to class/struct/union/generic type [C:\Users\Paul\code\tinyspeck\slack-winss
b\node_modules\ffi\build\ffi_bindings.vcxproj]
          type is 'unknown-type'
..\src\callback_info.cc(51): error C2039: 'Call' : is not a member of 'v8::Persistent<v8::Function,v8::NonCopyablePersistentTraits<T>>' [C:
\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          with
          [
              T=v8::Function
          ]
..\src\ffi.cc(28): error C2660: 'v8::Object::New' : function does not take 0 arguments [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modu
les\ffi\build\ffi_bindings.vcxproj]
..\src\callback_info.cc(51): error C2039: 'GetCurrent' : is not a member of 'v8::Context' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_m
odules\ffi\build\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(5886) : see declaration of 'v8::Context'
..\src\ffi.cc(31): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\b
uild\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(1890) : see declaration of 'v8::String'
..\src\callback_info.cc(51): error C2227: left of '->Global' must point to class/struct/union/generic type [C:\Users\Paul\code\tinyspeck\sl
ack-winssb\node_modules\ffi\build\ffi_bindings.vcxproj]
          type is 'unknown-type'
..\src\ffi.cc(31): error C3861: 'NewSymbol': identifier not found [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bin
dings.vcxproj]
..\src\callback_info.cc(51): error C3861: 'GetCurrent': identifier not found [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\bu
ild\ffi_bindings.vcxproj]
..\src\ffi.cc(32): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\b
uild\ffi_bindings.vcxproj]
          C:\Users\Paul\.slack\.node-gyp\.node-gyp\0.22.0\deps\v8\include\v8.h(1890) : see declaration of 'v8::String'
..\src\ffi.cc(32): error C3861: 'NewSymbol': identifier not found [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\build\ffi_bin
dings.vcxproj]
..\src\ffi.cc(33): error C2039: 'NewSymbol' : is not a member of 'v8::String' [C:\Users\Paul\code\tinyspeck\slack-winssb\node_modules\ffi\b
```

**Comment by TooTallNate** [comment]
If everyone could try and pull from master branch and compiling... we landed a PR today that should add compat for node v0.12 and io.js

**Comment by paulcbetts** [comment]
Master looks :gem: on Atom Shell

**Comment by TooTallNate** [comment]
v1.3.0 published to npm
