### ISSUE TITLE
ffi fails to load libgsl on node 0.12 on mac os x. Works fine on 0.10

### ISSUE THREAD

**Issue by manuelsantillan** [node-ffi/node-ffi#211]
ffi fails to load libgsl (GNU Scientific Library) on node 0.12 on mac os x. Same code works on node 0.10.
You can reproduce it by cloning https://github.com/solvver/ffi-test and issuing "node ffi-test.js"
Error stack is:

```
$ node ffi-test.js 
/Users/santillan/dev/solvview/ffi-bug/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: dlopen(libgsl.dylib, 2): Symbol not found: _cblas_caxpy
  Referenced from: /usr/local/lib/libgsl.dylib
  Expected in: flat namespace
 in /usr/local/lib/libgsl.dylib
    at new DynamicLibrary (/Users/santillan/dev/solvview/ffi-bug/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/santillan/dev/solvview/ffi-bug/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/Users/santillan/dev/solvview/ffi-bug/ffi-test.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kjunichi** [comment]
Hi,I tried it with node v0.12.7.

I don't know why node v0.10 resolove this dependencies.
I think that your error messages showed that you have to load libBLAS.dylib.
()

```js
var ref=require("ref")
var ArrayType=require("ref-array")
var ffi=require("ffi")

// /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
ffi.Library("libBLAS",{})
var DoubleArray=ArrayType(ref.types.double)
try{
    console.log("...Trying to load libgsl from library path. GNU Scientific Library should be installed in your system...")
    var libgsl=ffi.Library("libgsl", {"gsl_stats_mean":["double", [DoubleArray, "int", "int"]]})
    console.log("...libgsl loaded")
} catch (err){
    console.log("...libgsl is not installed in your system, trying to load './libgsl.dylib', a MAC OS X compiled version...")
    try{
    var libgsl=ffi.Library("./libgsl.dylib", {"gsl_stats_mean":["double", [DoubleArray, "int", "int"]]})
        console.log("...libgsl loaded")
    } catch(err){
            console.log(err)
        console.log("...No libgsl available in your system. Please download and install a suitable version from https://www.gnu.org/software/gsl/")
        console.log("...Quiting with error code 1")
        process.exit(1)
    }

}
console.log("...Starting test...")
var res=libgsl.gsl_stats_mean(new DoubleArray([3.2,3.2,3.2]), 1, 3);
if(res==3.2) console.log("TEST SUCCESS. Calculated mean equals expected 3.2 value")
else console.log("TEST FAIL. Mean should be 3.2 but is", res)
```

then, My console shows this.

```txt
...Trying to load libgsl from library path. GNU Scientific Library should be installed in your system...
...libgsl loaded
...Starting test...
TEST SUCCESS. Calculated mean equals expected 3.2 value
```

**Comment by manuelsantillan** [comment]
Tested your approach and it works. However, when going to AWS linux it does not work. I've succesfully used #80 tips to get it working. Just load libcblas with RTLD_NOW and RTLD_GLOBAL flags. Closing the issue.
