### ISSUE TITLE
Build failure with nan 2.0.0

### ISSUE THREAD

**Issue by feldgendler** [node-ffi/node-ffi#215]
Today nan 2.0.0 has been released, and ffi doesn't compile anymore:

```
$ npm install sleep
|
> sleep@2.0.0 install /home/alexey/node_modules/sleep
> node-gyp rebuild

make: Entering directory `/home/alexey/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Sleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:36:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../sleep.cc:38:7: error: ‘args’ was not declared in this scope
   if (args.Length() < 1 || !args[0]->IsUint32()) {
       ^
../sleep.cc:39:54: error: ‘NanThrowError’ was not declared in this scope
     return NanThrowError("Expected number of seconds");
                                                      ^
../sleep.cc:39:54: error: return-statement with a value, in function returning 'void' [-fpermissive]
../sleep.cc:42:9: error: ‘args’ was not declared in this scope
   sleep(args[0]->Uint32Value());
         ^
../sleep.cc:44:22: error: ‘NanReturnUndefined’ was not declared in this scope
   NanReturnUndefined();
                      ^
../sleep.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE USleep(Nan::NAN_METHOD_ARGS_TYPE)’:
../sleep.cc:48:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../sleep.cc:50:7: error: ‘args’ was not declared in this scope
   if (args.Length() < 1 || !args[0]->IsUint32()) {
       ^
../sleep.cc:51:59: error: ‘NanThrowError’ was not declared in this scope
     return NanThrowError("Expected number of microseconds");
                                                           ^
../sleep.cc:51:59: error: return-statement with a value, in function returning 'void' [-fpermissive]
../sleep.cc:54:10: error: ‘args’ was not declared in this scope
   usleep(args[0]->Uint32Value());
          ^
../sleep.cc:56:22: error: ‘NanReturnUndefined’ was not declared in this scope
   NanReturnUndefined();
                      ^
../sleep.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../sleep.cc:61:16: error: ‘NanNew’ was not declared in this scope
   exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
                ^
../sleep.cc:61:29: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
                             ^
../sleep.cc:61:64: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
                                                                ^
../sleep.cc:61:74: error: request for member ‘GetFunction’ in ‘Sleep’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
   exports->Set(NanNew<String>("sleep"), NanNew<FunctionTemplate>(Sleep)->GetFunction());
                                                                          ^
../sleep.cc:62:29: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<String>("usleep"), NanNew<FunctionTemplate>(USleep)->GetFunction());
                             ^
../sleep.cc:62:65: error: expected primary-expression before ‘>’ token
   exports->Set(NanNew<String>("usleep"), NanNew<FunctionTemplate>(USleep)->GetFunction());
                                                                 ^
../sleep.cc:62:76: error: request for member ‘GetFunction’ in ‘USleep’, which is of non-class type ‘Nan::NAN_METHOD_RETURN_TYPE(Nan::NAN_METHOD_ARGS_TYPE) {aka void(const Nan::FunctionCallbackInfo<v8::Value>&)}’
   exports->Set(NanNew<String>("usleep"), NanNew<FunctionTemplate>(USleep)->GetFunction());
                                                                            ^
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory `/home/alexey/node_modules/sleep/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.0-2-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alexey/node_modules/sleep
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@2.0.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.0.0-2-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sleep"
npm ERR! cwd /home/alexey
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by feldgendler** [comment]
The API has been changed significantly, and ffi will probably need substantial changes. Meanwhile, please depend on nan "<2.0.0" so that ffi can be installed.

**Comment by unbornchikken** [comment]
@TooTallNate Do you have time to do it? Just a package.json fix. 

Meanwhile I started to work on nan2 support.

**Comment by feldgendler** [comment]
Pull request #216.
