### ISSUE TITLE
ffi package giving error on Windows machine

### ISSUE THREAD

**Issue by cjpraful** [node-ffi/node-ffi#258]
my application using ffi module works fine in ubuntu. When i tried to deploy the in Windows machine it showed below error

```
> node server.js
D:\home\site\wwwroot
D:\home\site\wwwroot\node_modules\ffi\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: %1 is not a valid Win32 application.

D:\home\site\wwwroot\node_modules\ffi\node_modules\ref\build\Release\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (D:\home\site\wwwroot\node_modules\ffi\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\ffi\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

I removed ffi module and tried npm  install ffi again in windows machine it too didnt work. 

```
 npm install ffi
D:\home\site\wwwroot
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\npm\2.11.2\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files (x86)\\npm\\2.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\home\site\wwwroot\node_modules\ffi
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Windows_NT 6.2.9200
```

Could you please provide your thought on this issue

**Comment by TooTallNate** [comment]
You need to install Visual Studio, Python, and the rest of the native addon build requirements: https://github.com/nodejs/node-gyp#installation

**Comment by cjpraful** [comment]
Is there any other workaround other than installing Visual Studio .Coz its huge size to download and install.
Also could you please provide input why Visual studio is required or  why npm install ffi failed

**Comment by TooTallNate** [comment]
Sorry, I know it sucks, but native addons (ones written in C++ code) need to be compiled in order to work with Node. node-ffi is one of those packages. Compiling requires Visual Studio since that's what Node itself gets compiled with.

Which library/DLL are you attempting to interact with, out of curiosity?
