### ISSUE TITLE
Process fail after hundred callback calls

### ISSUE THREAD

**Issue by MaMazav** [node-ffi/node-ffi#265]
I've tried a simple program in which a shared library calls a javascript callback.
After some hundreds of calls, the process exits. Sometimes I get a "garbage collected" error message and sometimes "Segmentation fault". I've added a process.exit callback to avoid the GC issue mentioned in previous issues but the problem remains.
Analyzing the output, it seems like the process exits before the GC error. My guess is that this is either a memory usage issue in ffi lib or I forgot something very important...

Here is my library code (file try.c):

    #include <stdio.h>

    typedef int (*CallbackType)(int);

    CallbackType callback;

    void setCallback(CallbackType);
    void callCallback(int);
    void clearCallback();

    void setCallback(CallbackType callback_) {
        callback = callback_;
    }

    void clearCallback() {
        callback = NULL;
    }

    void callCallback(int x) {
        if (callback == NULL) {
            printf("(NATIVE) Callback has already been cleared\n");
            return;
        }
        printf("(NATIVE) Calling callback...\n");
        callback(x + 1);
        printf("(NATIVE) Callback called.\n");
    }

The C code above is compiled in Ubuntu by:

	gcc -fPIC -shared -Wl,-soname,libtry.so -o libtry.so try.c

Here is my node.js code (app.js):

    var ref = require('ref');
    var ffi = require('ffi');
    var refArray = require('ref-array');

    var CallbackType = ffi.Function(ref.types.int, [ref.types.int]);

    //var LIB = './libtry_threaded';
    var LIB = './libtry';

    var libtry = ffi.Library(LIB, {
        'setCallback': [ ref.types.void, [CallbackType] ],
        'callCallback': [ ref.types.void, [ref.types.int] ],
        'clearCallback': [ ref.types.void, [] ]
    });

    var lastValue = 1;
    var numCalls = 0;
    var returned = true;

    setInterval(function() {
        if (returned) {
            returned = false;
            libtry.callCallback(lastValue);
        }
    }, 1);

    var callback = function callback(x) {
        ++numCalls;
        console.log('(NODE) returned: ' + x + ', numCalls: ' + numCalls);
        lastValue = x;
        returned = true;
    }

    libtry.setCallback(callback);

    process.on('exit', function() {
        console.log('(NODE) Process exit!');
        libtry.clearCallback();
        console.log('(NODE) Cleared callback');
        callback;
    });

Here are some last lines of outputs I see.

Example 1 - GC Error:

    (NATIVE) Calling callback...
    (NODE) returned: 328, numCalls: 327
    (NATIVE) Callback called.
    (NATIVE) Calling callback...
    (NODE) returned: 329, numCalls: 328
    (NATIVE) Callback called.
    (NATIVE) Calling callback...
    (NODE) returned: 330, numCalls: 329
    (NATIVE) Callback called.
    (NATIVE) Calling callback...
    (NATIVE) Callback called.
    (NODE) Process exit!
    (NODE) Cleared callback
    /home/idan/dev/tmp/node_modules/ffi/lib/_foreign_function.js:59
        bindings.ffi_call(cif, funcPtr, result, argsList)
                 ^
    Error: ffi fatal: callback has been garbage collected!
        at Error (native)
        at Object.ForeignFunction.proxy [as callCallback] (/home/idan/dev/tmp/node_modules/ffi/lib/_foreign_function.js:59:14)
        at null.<anonymous> (/home/idan/dev/tmp/app.js:23:16)
        at wrapper [as _onTimeout] (timers.js:274:14)
        at Timer.listOnTimeout (timers.js:119:15)

Example 2 - Seg. fault:

    (NATIVE) Calling callback...
    (NODE) returned: 326, numCalls: 325
    (NATIVE) Callback called.
    (NATIVE) Calling callback...
    (NODE) returned: 327, numCalls: 326
    (NATIVE) Callback called.
    (NATIVE) Calling callback...
    Segmentation fault (core dumped)

**Comment by TooTallNate** [comment]
This is probably a duplicate of #241.

**Comment by lmangani** [comment]
I'm experiencing the very same issue with a similar implementation, apparently unaffected by #241 were there any other changes required for this use case? Thanks in advance!

**Comment by mabukar** [comment]
I'm also experiencing exactly the very same issue! Callbacks being GCed even though there're extra references ("ffi fatal: callback has been garbage collected!")

@TooTallNate: Would you be kind enough to look into this?

Sample code:

var firstCB = FFI.Function("void", ["int", "int"]);
var secondCB = FFI.Function("int", ["int"]);

var symbols= {
       "myFunc": ["int", ["int", firstCB, secondCB, "pointer"]]
};
 var mylib = new FFI.Library("./mylib", symbols);

// An extra reference to the callbacks to avoid GC
process.on('exit', function() {
    firstCB;
    secondCB;
});

**Comment by lmangani** [comment]
@mabukar coming back to this after a long time, curious if you ever found a solution for your case?

**Comment by mabukar** [comment]
@lmangani, sorry for the late response but I haven't been able to find solution for the case yet. Sometimes the process exits silently without any traces or errors.

**Comment by lmangani** [comment]
@mabukar same here - just ended up wrapping it in an (expensive) try/catch loop and loosing an iteration. Thanks for taking the time to reply!

**Comment by mabukar** [comment]
@lmangani No problem. Care to share an example of the try/catch trick?

**Comment by lmangani** [comment]
@mabukar barely using a try/catch wrapper as any other around the ffi callback, of course not preventing the issue per-se, ie:
```
	try { ffi_library(function(id,p){ ... }); } catch(e) { errors++; }
```
