### ISSUE TITLE
Build failure due to Python script

### ISSUE THREAD

**Issue by jdfreder** [node-ffi/node-ffi#266]
```
cc '-DNODE_GYP_MODULE_NAME=ffi' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DPIC' '-DFFI_BUILDING' '-DHAVE_CONFIG_H' '-DNDEBUG' -I/Users/jon/.node-gyp/4.2.1/include/node -I/Users/jon/.node-gyp/4.2.1/src -I/Users/jon/.node-gyp/4.2.1/deps/uv/include -I/Users/jon/.node-gyp/4.2.1/deps/v8/include -I../deps/libffi/include -I../deps/libffi/config/mac/x64  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o.d.raw  -c -o Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o ../deps/libffi/src/x86/darwin64.S
  rm -f Release/libffi.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/libffi.a Release/obj.target/ffi/deps/libffi/src/prep_cif.o Release/obj.target/ffi/deps/libffi/src/types.o Release/obj.target/ffi/deps/libffi/src/raw_api.o Release/obj.target/ffi/deps/libffi/src/java_raw_api.o Release/obj.target/ffi/deps/libffi/src/closures.o Release/obj.target/ffi/deps/libffi/src/x86/ffi.o Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o Release/obj.target/ffi/deps/libffi/src/x86/darwin.o Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
Traceback (most recent call last):
  File "./gyp-mac-tool", line 612, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: can't use a string pattern on a bytes-like object
make: *** [Release/libffi.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jon/xmem/node_modules/ffi
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

I'm using Python2.7 to build

```
Jonathans-MacBook-Pro:xmem jon$ python2 --version
Python 2.7.9
```

NPM command

```
npm install --save ffi --loglevel verbose --python=python2
```

**Comment by jdfreder** [comment]
Turns out that this was because `python` on my machine pointed to 3.x...  Which implied the `--python` flag simply does not work.  The workaround was to temporarily point python to python2.

**Comment by unbornchikken** [comment]
This issue isn't realted to ffi, please open up another thread at npm or node-gyp's repo.
