### ISSUE TITLE
Run to Electron 0.35.4 - Error listener must be a function

### ISSUE THREAD

**Issue by roman-sopov** [node-ffi/node-ffi#270]
Uncaught Exception:
TypeError: listener must be a function
    at process.once (events.js:251:11)
    at Object.<anonymous> (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\atom.asar\browser\api\lib\web-contents.js:151:11)
    at Object.<anonymous> (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\atom.asar\browser\api\lib\web-contents.js:160:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\atom.asar\browser\lib\guest-view-manager.js:8:17)

**Comment by unbornchikken** [comment]
Why do you belive that this issue related to ffi module?

**Comment by roman-sopov** [comment]
I require('ffi') and get errors. What's wrong?

**Comment by unbornchikken** [comment]
I'm not familiar with Electrom, but I'm assuming that you're requiring ffi module in a context when there is not supposed to be node.js modules. I believe that they name it as renderer process.

**Comment by roman-sopov** [comment]
Kill processs and rerun app, get errors:

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\build\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\build\Debug\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\build\Release\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\out\Debug\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\Debug\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\out\Release\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\Release\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\build\default\binding.node
 → C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\compiled\4.1.1\win32\ia32\binding.node
    at bindings (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\GitHub\Electron\electron-v0.35.4-win32-ia32\resources\default_app\main.js:1:90)
    at Module._compile (module.js:434:26)

**Comment by TooTallNate** [comment]
Did you follow the instructions here? https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
