### ISSUE TITLE
DLL initialization routine failed

### ISSUE THREAD

**Issue by xclw** [node-ffi/node-ffi#297]
I am using win 10 x64
I have followed your install destruction, but contiue get "a dynamic linked library (DLL) initialization routine failed" error when call "require('fii');", plz help me.

**Comment by MiklerGM** [comment]
I have the same problem(w10 x64), when running node-ffi with electron 0.37.2. But i am able to use node-ffi without electron with no issue

**Comment by PetrSnobelt** [comment]
electron-rebuild help me, thank you :+1:

**Comment by everrr1025** [comment]
hi @MiklerGM and  @xclw , i am facing the same issue now and it is killing me. in your comments 'rebuild native module', doest it mean, after install ffi, then we need to rebuild ffi by electron-rebuild? however, i tried it out by executing ~/node_modules/.bin/electron-rebuild, but i get the error below, any suggestion is appreciate.

> E:\development\electron-app\electron-quick-start\node_modules\.bin>electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v1.4.10/iojs-v1.4.10.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: self signed certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:586:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\development\\electron-app\\electron-quick-start\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--target=1.4.10" "--arch=x64" "--dist-url=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist"
gyp ERR! cwd E:\development\electron-app\electron-quick-start\node_modules\.bin
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by everrr1025** [comment]
yes, finally ,electron-rebuild --force worked for me, but make sure you are never behind a proxy!!!
i always get ssl every while i am with a proxy.
