### ISSUE TITLE
Doesn't build on ARMv8(

### ISSUE THREAD

**Issue by k1tzu** [node-ffi/node-ffi#299]
$node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.10.1 | linux | arm64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ak/tmpnode/node-ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ak/.node-gyp/5.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ak/.node-gyp/5.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ak/tmpnode/node-ffi',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ak/tmpnode/node-ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
../deps/libffi/src/prep_cif.c:26:17: fatal error: ffi.h: No such file or directory
compilation terminated.
deps/libffi/ffi.target.mk:106: recipe for target 'Release/obj.target/ffi/deps/libffi/src/prep_cif.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
make: Leaving directory '/home/ak/tmpnode/node-ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.14.29-18-ARCH
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ak/tmpnode/node-ffi
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3

**Comment by k1tzu** [comment]
All I got after giving it a correct libffi compiled from git and this was a dead end for me:
CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:16:16: error: expected constructor, destructor, or type conversion before '(' token
 NAN_MODULE_INIT(FFI::InitializeStaticFunctions) {
                ^
../src/ffi.cc:35:16: error: expected constructor, destructor, or type conversion before '(' token
 NAN_MODULE_INIT(FFI::InitializeBindings) {
                ^
../src/ffi.cc:164:11: error: expected constructor, destructor, or type conversion before '(' token
 NAN_METHOD(FFI::FFIPrepCif) {

**Comment by mbroadst** [comment]
I'm actually running into this issue myself while installing node-ffi as a dependency within a cross-compiling yocto build. From reading through the source I can't actually tell where in the process `ffi.h` is created from the existing `ffi.h.in`, could one of the maintainers speak to this? Whatever is going on in both of our environments is preventing that from being created it seems..

**Comment by mbroadst** [comment]
Oh I see, the configs are pregenerated and included here: https://github.com/node-ffi/node-ffi/blob/master/deps/libffi/libffi.gyp#L109

so there must just be an issue related to those variables not being set properly in my build system

**Comment by rookiezh** [comment]
> All I got after giving it a correct libffi compiled from git and this was a dead end for me: CXX(target) Release/obj.target/ffi_bindings/src/ffi.o ../src/ffi.cc:16:16: error: expected constructor, destructor, or type conversion before '(' token NAN_MODULE_INIT(FFI::InitializeStaticFunctions) { ^ ../src/ffi.cc:35:16: error: expected constructor, destructor, or type conversion before '(' token NAN_MODULE_INIT(FFI::InitializeBindings) { ^ ../src/ffi.cc:164:11: error: expected constructor, destructor, or type conversion before '(' token NAN_METHOD(FFI::FFIPrepCif) {

How did you solve it in the end?
