### ISSUE TITLE
problem :Error: Dynamic Linking Error: Win32 error 127 ?

### ISSUE THREAD

**Issue by zhangzhichengyu** [node-ffi/node-ffi#301]
`Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (C:\Users\anthony\Desktop\demo-nwjs-v0.12.0\node_modules\ffi\lib\dynamic_library.js:112:11)
    at C:\Users\anthony\Desktop\demo-nwjs-v0.12.0\node_modules\ffi\lib\library.js:50:19
    at Array.forEach (native)
    at new Library (C:\Users\anthony\Desktop\demo-nwjs-v0.12.0\node_modules\ffi\lib\library.js:47:28)`

**Comment by hxfdarling** [comment]
not found method in you DLL

**Comment by topwood** [comment]
your dll is win32 while your node is x64?

**Comment by marcholterman** [comment]
Getting the same error as @zhangzhichengyu . My ddl and node version are both 64-bit.

**Comment by marcholterman** [comment]
My mistake. Name mismatch. Error 127 might also mean that the required symbol is not found.

**Comment by gbaumgart** [comment]
might it be possible to ignore not found symbols ? I usually setup bigger maps, see [here](https://github.com/gbaumgart/vlc-ffi/blob/master/lib/libvlc.js#L53)

sometimes the library doesn't have the symbol and its not biggy for me, at least.
