### ISSUE TITLE
some problmes about npm install ffi on windows

### ISSUE THREAD

**Issue by siduoge** [node-ffi/node-ffi#308]
```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\JCS>e:

E:\>cd E:\Users\JCS\Desktop\paikankan\work\test_1

E:\Users\JCS\Desktop\paikankan\work\test_1>npm install ffi

> ref@1.3.2 install E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref
> node-gyp rebuild


E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref>if not defined npm_c
onfig_node_gyp (node "C:\Users\JCS\AppData\Roaming\npm\node_modules\npm\bin\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node ""
rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
  win_delay_load_hook.c
C:\Users\JCS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win
_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; diffe
rent type modifiers [E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\re
f\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\JCS\AppData\Roaming\npm\node
_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "J:\\tools\\nodejs\\node.exe" "C:\\Users\\JCS\\AppData\\Roaming
\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Users\JCS\Desktop\paikankan\work\test_1\node_modules\ref
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
application-name@0.0.1 E:\Users\JCS\Desktop\paikankan\work\test_1
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "J:\\tools\\nodejs\\node.exe" "C:\\Users\\JCS\\AppData\\Roaming\\n
pm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ffi"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! ref@1.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ref
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Users\JCS\Desktop\paikankan\work\test_1\npm-debug.log
npm ERR! code 1

E:\Users\JCS\Desktop\paikankan\work\test_1>
```

**Comment by siduoge** [comment]
the error is always  __pfnDliNotifyHook2   redefinition,but I have do all the reqirements. The python I have instal correctly ,the vs2015 and .net4.5.1 are all installed in my computer . I just dont know where is  wrong?

**Comment by addaleax** [comment]
`npm install -g npm@next`?

**Comment by TooTallNate** [comment]
Ya this is caused by an older version of node-gyp that npm is using. Either update npm or node-gyp or both.

**Comment by kroggen** [comment]
Here is how to do it:

http://stackoverflow.com/questions/38149603/npm-install-fails-with-error-c2373-with-vs2015-update-3
