### ISSUE TITLE
Installation from github fails

### ISSUE THREAD

**Issue by MattiasMM** [node-ffi/node-ffi#309]
Installation from github fails

```
npm version: 2.15.9
node-gyp version node-gyp@3.4.0  C:\Program Files\nodejs\node_modules\node-gyp
nodejs version: v0.10.33
 
PYTHON and PYTHONHOME set to pthon2.7 64 bit
PYTHON=C:\Program Files\Python27\python.exe
PYTHONHOME=C:\Program Files\Python27\
```

**This is output in the windows command prompt:**

```
Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

E:\node_modules>git clone git://github.com/node-ffi/node-ffi.git
Cloning into 'node-ffi'...
remote: Counting objects: 4729, done.
remote: Total 4729 (delta 0), reused 0 (delta 0), pack-reused 4729
Receiving objects: 100% (4729/4729), 3.28 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (2290/2290), done.
Checking connectivity... done.

E:\node_modules>cd node-ffi

E:\node_modules\node-ffi>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@0.10.33 | win32 | x64
gyp ERR! configure error
**gyp ERR! stack Error: Command failed: ImportError: No module named site**
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:648:15)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:756:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:
5)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\node_modules\node-ffi
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by TooTallNate** [comment]
Are you able to install _any_ native addons? Try `npm install ref`…

**Comment by MattiasMM** [comment]
Hi, the solution was to make sure that npm 3 , and not 3, was installed.
+
Correcting and double checking the path variables of python2.7. It turned
out that uninstall of python didn't reset env. Variables properly on my
windows server.

**Comment by MattiasMM** [comment]
Hi, the solution was to make sure that npm 3 , and not 2, was installed.
+
Correcting and double checking the path variables of python2.7. It turned
out that uninstall of python didn't reset env. Variables properly on my
windows server.

Hide quoted text
