### ISSUE TITLE
Not finding functions that are in the dylib

### ISSUE THREAD

**Issue by squishybanana04** [node-ffi/node-ffi#364]
This is a snippet from my library:
```c++
float** simplex(int w, int h,
                unsigned int octaves = 4, float scale = 0.1,
                FastNoise::FractalType fractalType = FastNoise::FBM,
                float lacunarity = 2.0, float gain = 0.5) {
    
    noise.SetNoiseType(FastNoise::SimplexFractal);
    
    setFractalSettings(octaves, scale, fractalType, lacunarity, gain);
    
    //Get the noise
    float** output = 0;
    output = new float*[w];
    for (int x = 0; x < w; x++) {
        output[x] = new float[h];
        for (int y = 0; y < h; y++) {
            output[x][y] = noise.GetNoise(x * scale, y * scale + 1000);
        }
    }
    return equalize(output, 0, 1, w, h);
}
```
I compiled it with `g++ -c main.cpp FastNoise.h FastNoise.cpp -std=c++11`
`g++ -dynamiclib -flat_namespace *.o -o libnoise.dylib`

And when I run node ffi in javascript it tells me
```
Error: Dynamic Symbol Retrieval Error: dlsym(0x1039008d0, simplex): symbol not found
    at DynamicLibrary.get (/Users/jamiewaese/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /Users/jamiewaese/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at Object.Library (/Users/jamiewaese/node_modules/ffi/lib/library.js:47:28)
    at repl:1:16
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
```
My javascript code is
```javascript
require('ffi').Library('./libnoise', {'simplex': ['float**', ['int', 'int', 'float']]});
```

**Comment by squishybanana04** [comment]
I just tested the example and it doesn't work either

**Comment by squishybanana04** [comment]
I didn't do -undefined suppress. When I tried it with that it worked.
