### ISSUE TITLE
Dynamic Linking Error while linking SNAP (C++ library)

### ISSUE THREAD

**Issue by kkulkarni1997** [node-ffi/node-ffi#365]
I'm trying to link the SNAP C++ (https://snap.stanford.edu/snap/) library via ffi with: 

`var libm = ffi.Library('snap-core')`

but am getting the following error message: 

`Error: Dynamic Linking Error: dlopen(snap-core.dylib, 2): image not found
    at new DynamicLibrary (/Users/Kulkarni/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/Kulkarni/node_modules/ffi/lib/library.js:45:12)
    at repl:1:16
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)`

Not sure how to resolve this...

**Comment by kimjuny** [comment]
Hi, did you fix this problem?
