### ISSUE TITLE
windows xp Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by serkanp** [node-ffi/node-ffi#386]
hi i am using ffi in my project bassaudio. 
it works in windows 7, 8,10 , macosx all versions, linux and arm linux. 
but on windows xp sp3(all updates are installed) i got a strange error. 

Error: The specified procedure could not be found.
\\ ?\C:\codes\deneme\node_modules\ffi\build\Release\ffi_bindings.node
the chars at the beginning \\? is causing the problem i think and it refers to node_modules\ffi\node_modules\bindings\bindings.js:83
but bindings.js only requires ffi_bindings.node binary. 

here is the the output:

C:\codes\deneme>node -v
v4.8.2

C:\codes\deneme>npm -v
2.15.11

C:\codes\deneme>node app.js
C:\codes\deneme\node_modules\ffi\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: The specified procedure could not be found.
\\ ?\C:\codes\deneme\node_modules\ffi\build\Release\ffi_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (C:\codes\deneme\node_modules\ffi\node_modules\bindings\bindings
.js:76:44)
    at Object.<anonymous> (C:\codes\deneme\node_modules\ffi\lib\bindings.js:2:37
)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by Elainehxx** [comment]
I encountered the same problem with you, Can you to solve the problem, Please  tell  me how to solve,thank you

**Comment by CNDonny** [comment]
The same proble. I hate XP

**Comment by jakeyChen1994** [comment]
> hi i am using ffi in my project bassaudio.
> it works in windows 7, 8,10 , macosx all versions, linux and arm linux.
> but on windows xp sp3(all updates are installed) i got a strange error.
> 
> Error: The specified procedure could not be found.
> \ ?\C:\codes\deneme\node_modules\ffi\build\Release\ffi_bindings.node
> the chars at the beginning \? is causing the problem i think and it refers to node_modules\ffi\node_modules\bindings\bindings.js:83
> but bindings.js only requires ffi_bindings.node binary.
> 
> unfortunately, my app is used on more then 10.000 computers that are macos, windows, linux, raspberry pi etc..
> %30 of my clients are still using windows xp. and i can't say them to change their current computers :)
> we are serving legal music to shops , malls etc.. so most of them still wanted to use their own office computers which are still windows xp sp3.
> i have various visual studios on different os'.
> i have currently visual studio 2015 on windows 10 x64, but also have visual studio 2017, 2013, 2010 etc.
> i couldn't compile it on xp as you may guess :)
> i compiled it on windows 7 32bit with visual studio 2010 and compile tools. then i copied folder to windows xp and tested there
> 
> here is the the output on windows xp sp3 32bit:
> 
> C:\codes\deneme>node -v
> v4.8.2
> 
> C:\codes\deneme>npm -v
> 2.15.11
> 
> C:\codes\deneme>node app.js
> C:\codes\deneme\node_modules\ffi\node_modules\bindings\bindings.js:83
> throw e
> ^
> 
> Error: The specified procedure could not be found.
> \ ?\C:\codes\deneme\node_modules\ffi\build\Release\ffi_bindings.node
> at Error (native)
> at Object.Module._extensions..node (module.js:434:18)
> at Module.load (module.js:343:32)
> at Function.Module._load (module.js:300:12)
> at Module.require (module.js:353:17)
> at require (internal/module.js:12:17)
> at bindings (C:\codes\deneme\node_modules\ffi\node_modules\bindings\bindings
> .js:76:44)
> at Object. (C:\codes\deneme\node_modules\ffi\lib\bindings.js:2:37
> )
> at Module._compile (module.js:409:26)
> at Object.Module._extensions..js (module.js:416:10)

I hava resolved this problem,enter the src dir and delete this two lines:

errorMode = GetErrorMode();
SetErrorMode(errorMode | SEM_FAILCRITICALERRORS

And then exec "node-gyp rebuild",the library after rebuild can work correct on windows xp 
@Elainehxx @CNDonny you can try
