### ISSUE TITLE
Dynamic Symbol Retrieval Error: libtensorflow.so: undefined symbol: TF_GraphImportGraphDefOptionsRemapControlDependency

### ISSUE THREAD

**Issue by basickarl** [node-ffi/node-ffi#389]
```
karl@karl-Dell-Precision-M3800:~/dev/node/tensorflow$ npm start

> tensorflow@1.0.0 start /home/karl/dev/node/tensorflow
> bash ./src/start.sh

/home/karl/dev/node/tensorflow/node_modules/ffi/lib/library.js:0

Error: Dynamic Symbol Retrieval Error: /home/karl/dev/node/tensorflow/src/addons/tensorflow/src/lib/libtensorflow.so: undefined symbol: TF_GraphImportGraphDefOptionsRemapControlDependency
    at DynamicLibrary.get (/home/karl/dev/node/tensorflow/node_modules/ffi/lib/dynamic_library.js:112:11)
    at /home/karl/dev/node/tensorflow/node_modules/ffi/lib/library.js:50:19
    at Array.forEach (native)
    at new Library (/home/karl/dev/node/tensorflow/node_modules/ffi/lib/library.js:47:28)
    at Object.<anonymous> (/home/karl/dev/node/tensorflow/src/libs/bindings_tf.js:166:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

And in my bindings_tf.js file:
```
  //..more code
  TF_GraphImportGraphDefOptionsRemapControlDependency: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
    ref.types.CString,
    TF_OperationPtr,
  ]],
  //..more code
```

If you need any other just say.

**Comment by jmanteigueiro** [comment]
Are the other types defined? 

TF_ImportGraphDefOptionsPtr and TF_OperationPtr,

**Comment by basickarl** [comment]
@jmanteigueiro Here is the full file :)

```
var FFI = require('ffi'),
  ArrayType = require('ref-array'),
  Struct = require('ref-struct'),
  ref = require('ref');

var voidPtr = ref.refType(ref.types.void);

exports.CONSTANTS = {
  '': {
    TF_FLOAT: 1,
    TF_DOUBLE: 2,
    TF_INT32: 3,
    TF_UINT8: 4,
    TF_INT16: 5,
    TF_INT8: 6,
    TF_STRING: 7,
    TF_COMPLEX64: 8,
    TF_COMPLEX: 8,
    TF_INT64: 9,
    TF_BOOL: 10,
    TF_QINT8: 11,
    TF_QUINT8: 12,
    TF_QINT32: 13,
    TF_BFLOAT16: 14,
    TF_QINT16: 15,
    TF_QUINT16: 16,
    TF_UINT16: 17,
    TF_COMPLEX128: 18,
    TF_HALF: 19,
    TF_RESOURCE: 20,
    TF_OK: 0,
    TF_CANCELLED: 1,
    TF_UNKNOWN: 2,
    TF_INVALID_ARGUMENT: 3,
    TF_DEADLINE_EXCEEDED: 4,
    TF_NOT_FOUND: 5,
    TF_ALREADY_EXISTS: 6,
    TF_PERMISSION_DENIED: 7,
    TF_UNAUTHENTICATED: 16,
    TF_RESOURCE_EXHAUSTED: 8,
    TF_FAILED_PRECONDITION: 9,
    TF_ABORTED: 10,
    TF_OUT_OF_RANGE: 11,
    TF_UNIMPLEMENTED: 12,
    TF_INTERNAL: 13,
    TF_UNAVAILABLE: 14,
    TF_DATA_LOSS: 15,
    TF_ATTR_STRING: 0,
    TF_ATTR_INT: 1,
    TF_ATTR_FLOAT: 2,
    TF_ATTR_BOOL: 3,
    TF_ATTR_TYPE: 4,
    TF_ATTR_SHAPE: 5,
    TF_ATTR_TENSOR: 6,
    TF_ATTR_PLACEHOLDER: 7,
    TF_ATTR_FUNC: 8,
    '1': 'TF_FLOAT',
    '2': 'TF_DOUBLE',
    '3': 'TF_INT32',
    '4': 'TF_UINT8',
    '5': 'TF_INT16',
    '6': 'TF_INT8',
    '7': 'TF_STRING',
    '8': 'TF_COMPLEX64',
    '8': 'TF_COMPLEX',
    '9': 'TF_INT64',
    '10': 'TF_BOOL',
    '11': 'TF_QINT8',
    '12': 'TF_QUINT8',
    '13': 'TF_QINT32',
    '14': 'TF_BFLOAT16',
    '15': 'TF_QINT16',
    '16': 'TF_QUINT16',
    '17': 'TF_UINT16',
    '18': 'TF_COMPLEX128',
    '19': 'TF_HALF',
    '20': 'TF_RESOURCE',
    '0': 'TF_OK',
    '1': 'TF_CANCELLED',
    '2': 'TF_UNKNOWN',
    '3': 'TF_INVALID_ARGUMENT',
    '4': 'TF_DEADLINE_EXCEEDED',
    '5': 'TF_NOT_FOUND',
    '6': 'TF_ALREADY_EXISTS',
    '7': 'TF_PERMISSION_DENIED',
    '16': 'TF_UNAUTHENTICATED',
    '8': 'TF_RESOURCE_EXHAUSTED',
    '9': 'TF_FAILED_PRECONDITION',
    '10': 'TF_ABORTED',
    '11': 'TF_OUT_OF_RANGE',
    '12': 'TF_UNIMPLEMENTED',
    '13': 'TF_INTERNAL',
    '14': 'TF_UNAVAILABLE',
    '15': 'TF_DATA_LOSS',
    '0': 'TF_ATTR_STRING',
    '1': 'TF_ATTR_INT',
    '2': 'TF_ATTR_FLOAT',
    '3': 'TF_ATTR_BOOL',
    '4': 'TF_ATTR_TYPE',
    '5': 'TF_ATTR_SHAPE',
    '6': 'TF_ATTR_TENSOR',
    '7': 'TF_ATTR_PLACEHOLDER',
    '8': 'TF_ATTR_FUNC',
  },
};

var TF_Status = exports.TF_Status = voidPtr;
var TF_StatusPtr = exports.TF_StatusPtr = ref.refType(TF_Status);
var TF_Buffer = exports.TF_Buffer = Struct({
  data: voidPtr,
  length: ref.types.int32,
  data_deallocator: voidPtr,
});
var TF_BufferPtr = exports.TF_BufferPtr = ref.refType(TF_Buffer);
var TF_Tensor = exports.TF_Tensor = voidPtr;
var TF_TensorPtr = exports.TF_TensorPtr = ref.refType(TF_Tensor);
var int64_t = exports.int64_t = voidPtr;
var int64_tPtr = exports.int64_tPtr = ref.refType(int64_t);
var TF_SessionOptions = exports.TF_SessionOptions = voidPtr;
var TF_SessionOptionsPtr = exports.TF_SessionOptionsPtr = ref.refType(TF_SessionOptions);
var TF_Graph = exports.TF_Graph = voidPtr;
var TF_GraphPtr = exports.TF_GraphPtr = ref.refType(TF_Graph);
var TF_Operation = exports.TF_Operation = voidPtr;
var TF_OperationPtr = exports.TF_OperationPtr = ref.refType(TF_Operation);
var TF_Output = exports.TF_Output = Struct({
  oper: TF_Operation,
  index: ref.types.int32,
});
var TF_OutputPtr = exports.TF_OutputPtr = ref.refType(TF_Output);
var TF_OperationDescription = exports.TF_OperationDescription = voidPtr;
var TF_OperationDescriptionPtr = exports.TF_OperationDescriptionPtr = ref.refType(TF_OperationDescription);
var TF_DataType = exports.TF_DataType = voidPtr;
var TF_DataTypePtr = exports.TF_DataTypePtr = ref.refType(TF_DataType);
var TF_Input = exports.TF_Input = Struct({
  oper: TF_OperationPtr,
  index: ref.types.int32,
});
var TF_InputPtr = exports.TF_InputPtr = ref.refType(TF_Input);
var TF_AttrMetadata = exports.TF_AttrMetadata = Struct({
  is_list: ref.types.uchar,
  list_size: ref.types.long,
  type: ref.types.uint32,
  total_size: ref.types.long,
});
var TF_AttrMetadataPtr = exports.TF_AttrMetadataPtr = ref.refType(TF_AttrMetadata);
var TF_ImportGraphDefOptions = exports.TF_ImportGraphDefOptions = voidPtr;
var TF_ImportGraphDefOptionsPtr = exports.TF_ImportGraphDefOptionsPtr = ref.refType(TF_ImportGraphDefOptions);
var TF_WhileParams = exports.TF_WhileParams = Struct({
  ninputs: ref.types.int32,
  cond_graph: TF_GraphPtr,
  cond_inputs: TF_OutputPtr,
  cond_output: TF_Output,
  body_graph: TF_GraphPtr,
  body_inputs: TF_OutputPtr,
  body_outputs: TF_OutputPtr,
  name: ref.types.CString,
});
var TF_WhileParamsPtr = exports.TF_WhileParamsPtr = ref.refType(TF_WhileParams);
var TF_Session = exports.TF_Session = voidPtr;
var TF_SessionPtr = exports.TF_SessionPtr = ref.refType(TF_Session);
var TF_DeprecatedSession = exports.TF_DeprecatedSession = voidPtr;
var TF_DeprecatedSessionPtr = exports.TF_DeprecatedSessionPtr = ref.refType(TF_DeprecatedSession);
var TF_Library = exports.TF_Library = voidPtr;
var TF_LibraryPtr = exports.TF_LibraryPtr = ref.refType(TF_Library);

exports.libtensorflow = new FFI.Library('libtensorflow', {
  TF_Version: [ref.types.CString, [
  ]],
  TF_DataTypeSize: [ref.types.int32, [
    ref.types.uint32,
  ]],
  TF_NewStatus: [TF_Status, [
  ]],
  TF_DeleteStatus: [ref.types.void, [
    TF_StatusPtr,
  ]],
  TF_SetStatus: [ref.types.void, [
    TF_StatusPtr,
    ref.types.uint32,
    ref.types.CString,
  ]],
  TF_GetCode: [ref.types.uint32, [
    TF_StatusPtr,
  ]],
  TF_Message: [ref.types.CString, [
    TF_StatusPtr,
  ]],
  TF_NewBufferFromString: [TF_BufferPtr, [
    voidPtr,
    ref.types.int32,
  ]],
  TF_NewBuffer: [TF_BufferPtr, [
  ]],
  TF_DeleteBuffer: [ref.types.void, [
    TF_BufferPtr,
  ]],
  TF_GetBuffer: [TF_Buffer, [
    TF_BufferPtr,
  ]],
  TF_NewTensor: [TF_Tensor, [
    ref.types.uint32,
    int64_t,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    voidPtr,
    voidPtr,
  ]],
  TF_AllocateTensor: [TF_TensorPtr, [
    ref.types.uint32,
    int64_tPtr,
    ref.types.int32,
    ref.types.int32,
  ]],
  TF_DeleteTensor: [ref.types.void, [
    TF_TensorPtr,
  ]],
  TF_TensorType: [ref.types.uint32, [
    TF_TensorPtr,
  ]],
  TF_NumDims: [ref.types.int32, [
    TF_TensorPtr,
  ]],
  TF_Dim: [ref.types.long, [
    TF_TensorPtr,
    ref.types.int32,
  ]],
  TF_TensorByteSize: [ref.types.int32, [
    TF_TensorPtr,
  ]],
  TF_TensorData: [voidPtr, [
    TF_TensorPtr,
  ]],
  TF_StringEncode: [ref.types.int32, [
    ref.types.CString,
    ref.types.int32,
    ref.types.CString,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_StringDecode: [ref.types.int32, [
    ref.types.CString,
    ref.types.int32,
    voidPtr,
    ref.refType(ref.types.int32),
    TF_StatusPtr,
  ]],
  TF_StringEncodedSize: [ref.types.int32, [
    ref.types.int32,
  ]],
  TF_NewSessionOptions: [TF_SessionOptions, [
  ]],
  TF_SetTarget: [ref.types.void, [
    TF_SessionOptionsPtr,
    ref.types.CString,
  ]],
  TF_SetConfig: [ref.types.void, [
    TF_SessionOptionsPtr,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_DeleteSessionOptions: [ref.types.void, [
    TF_SessionOptionsPtr,
  ]],
  TF_NewGraph: [TF_Graph, [
  ]],
  TF_DeleteGraph: [ref.types.void, [
    TF_GraphPtr,
  ]],
  TF_GraphSetTensorShape: [ref.types.void, [
    TF_GraphPtr,
    TF_Output,
    int64_tPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_GraphGetTensorNumDims: [ref.types.int32, [
    TF_GraphPtr,
    TF_Output,
    TF_StatusPtr,
  ]],
  TF_GraphGetTensorShape: [ref.types.void, [
    TF_GraphPtr,
    TF_Output,
    int64_tPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_NewOperation: [TF_OperationDescription, [
    TF_GraphPtr,
    ref.types.CString,
    ref.types.CString,
  ]],
  TF_SetDevice: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
  ]],
  TF_AddInput: [ref.types.void, [
    TF_OperationDescriptionPtr,
    TF_Output,
  ]],
  TF_AddInputList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    TF_OutputPtr,
    ref.types.int32,
  ]],
  TF_AddControlInput: [ref.types.void, [
    TF_OperationDescriptionPtr,
    TF_OperationPtr,
  ]],
  TF_ColocateWith: [ref.types.void, [
    TF_OperationDescriptionPtr,
    TF_OperationPtr,
  ]],
  TF_SetAttrString: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
  ]],
  TF_SetAttrStringList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.refType(ref.types.int32),
    ref.types.int32,
  ]],
  TF_SetAttrInt: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.types.long,
  ]],
  TF_SetAttrIntList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    int64_tPtr,
    ref.types.int32,
  ]],
  TF_SetAttrFloat: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.types.float,
  ]],
  TF_SetAttrFloatList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.refType(ref.types.float),
    ref.types.int32,
  ]],
  TF_SetAttrBool: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.types.uchar,
  ]],
  TF_SetAttrBoolList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.refType(ref.types.uchar),
    ref.types.int32,
  ]],
  TF_SetAttrType: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    ref.types.uint32,
  ]],
  TF_SetAttrTypeList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    TF_DataType,
    ref.types.int32,
  ]],
  TF_SetAttrShape: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    int64_tPtr,
    ref.types.int32,
  ]],
  TF_SetAttrShapeList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.refType(ref.types.int32),
    ref.types.int32,
  ]],
  TF_SetAttrTensorShapeProto: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_SetAttrTensorShapeProtoList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.refType(ref.types.int32),
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_SetAttrTensor: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    TF_TensorPtr,
    TF_StatusPtr,
  ]],
  TF_SetAttrTensorList: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_SetAttrValueProto: [ref.types.void, [
    TF_OperationDescriptionPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_FinishOperation: [TF_OperationPtr, [
    TF_OperationDescriptionPtr,
    TF_StatusPtr,
  ]],
  TF_OperationName: [ref.types.CString, [
    TF_OperationPtr,
  ]],
  TF_OperationOpType: [ref.types.CString, [
    TF_OperationPtr,
  ]],
  TF_OperationDevice: [ref.types.CString, [
    TF_OperationPtr,
  ]],
  TF_OperationNumOutputs: [ref.types.int32, [
    TF_OperationPtr,
  ]],
  TF_OperationOutputType: [ref.types.uint32, [
    TF_Output,
  ]],
  TF_OperationOutputListLength: [ref.types.int32, [
    TF_OperationPtr,
    ref.types.CString,
    TF_StatusPtr,
  ]],
  TF_OperationNumInputs: [ref.types.int32, [
    TF_OperationPtr,
  ]],
  TF_OperationInputType: [ref.types.uint32, [
    TF_Input,
  ]],
  TF_OperationInputListLength: [ref.types.int32, [
    TF_OperationPtr,
    ref.types.CString,
    TF_StatusPtr,
  ]],
  TF_OperationInput: [TF_Output, [
    TF_Input,
  ]],
  TF_OperationOutputNumConsumers: [ref.types.int32, [
    TF_Output,
  ]],
  TF_OperationOutputConsumers: [ref.types.int32, [
    TF_Output,
    TF_InputPtr,
    ref.types.int32,
  ]],
  TF_OperationNumControlInputs: [ref.types.int32, [
    TF_OperationPtr,
  ]],
  TF_OperationGetControlInputs: [ref.types.int32, [
    TF_OperationPtr,
    voidPtr,
    ref.types.int32,
  ]],
  TF_OperationNumControlOutputs: [ref.types.int32, [
    TF_OperationPtr,
  ]],
  TF_OperationGetControlOutputs: [ref.types.int32, [
    TF_OperationPtr,
    voidPtr,
    ref.types.int32,
  ]],
  TF_OperationGetAttrMetadata: [TF_AttrMetadata, [
    TF_OperationPtr,
    ref.types.CString,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrString: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrStringList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    ref.refType(ref.types.int32),
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrInt: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    int64_tPtr,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrIntList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    int64_tPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrFloat: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    ref.refType(ref.types.float),
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrFloatList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    ref.refType(ref.types.float),
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrBool: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    ref.refType(ref.types.uchar),
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrBoolList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    ref.refType(ref.types.uchar),
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrType: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    TF_DataTypePtr,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrTypeList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    TF_DataTypePtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrShape: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    int64_tPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrShapeList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    ref.refType(ref.types.int32),
    ref.types.int32,
    int64_tPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrTensorShapeProto: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrTensorShapeProtoList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrTensor: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrTensorList: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_OperationGetAttrValueProto: [ref.types.void, [
    TF_OperationPtr,
    ref.types.CString,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_GraphOperationByName: [TF_OperationPtr, [
    TF_GraphPtr,
    ref.types.CString,
  ]],
  TF_GraphNextOperation: [TF_OperationPtr, [
    TF_GraphPtr,
    ref.refType(ref.types.int32),
  ]],
  TF_GraphToGraphDef: [ref.types.void, [
    TF_GraphPtr,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_NewImportGraphDefOptions: [TF_ImportGraphDefOptions, [
  ]],
  TF_DeleteImportGraphDefOptions: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
  ]],
  TF_ImportGraphDefOptionsSetPrefix: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
    ref.types.CString,
  ]],
  TF_ImportGraphDefOptionsAddInputMapping: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
    ref.types.CString,
    ref.types.int32,
    TF_Output,
  ]],
  // TF_GraphImportGraphDefOptionsRemapControlDependency: [ref.types.void, [
  //   TF_ImportGraphDefOptionsPtr,
  //   ref.types.CString,
  //   TF_OperationPtr,
  // ]],
  TF_ImportGraphDefOptionsAddControlDependency: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
    TF_OperationPtr,
  ]],
  TF_ImportGraphDefOptionsAddReturnOutput: [ref.types.void, [
    TF_ImportGraphDefOptionsPtr,
    ref.types.CString,
    ref.types.int32,
  ]],
  TF_ImportGraphDefOptionsNumReturnOutputs: [ref.types.int32, [
    TF_ImportGraphDefOptionsPtr,
  ]],
  TF_GraphImportGraphDefWithReturnOutputs: [ref.types.void, [
    TF_GraphPtr,
    TF_BufferPtr,
    TF_ImportGraphDefOptionsPtr,
    TF_OutputPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_GraphImportGraphDef: [ref.types.void, [
    TF_GraphPtr,
    TF_BufferPtr,
    TF_ImportGraphDefOptionsPtr,
    TF_StatusPtr,
  ]],
  TF_OperationToNodeDef: [ref.types.void, [
    TF_OperationPtr,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_NewWhile: [TF_WhileParams, [
    TF_GraphPtr,
    TF_OutputPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_FinishWhile: [ref.types.void, [
    TF_WhileParamsPtr,
    TF_StatusPtr,
    TF_OutputPtr,
  ]],
  TF_AbortWhile: [ref.types.void, [
    TF_WhileParamsPtr,
  ]],
  TF_NewSession: [TF_Session, [
    TF_GraphPtr,
    TF_SessionOptionsPtr,
    TF_StatusPtr,
  ]],
  TF_LoadSessionFromSavedModel: [TF_SessionPtr, [
    TF_SessionOptionsPtr,
    TF_BufferPtr,
    ref.types.CString,
    voidPtr,
    ref.types.int32,
    TF_GraphPtr,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_CloseSession: [ref.types.void, [
    TF_SessionPtr,
    TF_StatusPtr,
  ]],
  TF_DeleteSession: [ref.types.void, [
    TF_SessionPtr,
    TF_StatusPtr,
  ]],
  TF_SessionRun: [ref.types.void, [
    TF_SessionPtr,
    TF_BufferPtr,
    TF_OutputPtr,
    voidPtr,
    ref.types.int32,
    TF_OutputPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_SessionPRunSetup: [ref.types.void, [
    TF_SessionPtr,
    TF_OutputPtr,
    ref.types.int32,
    TF_OutputPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    voidPtr,
    TF_StatusPtr,
  ]],
  TF_SessionPRun: [ref.types.void, [
    TF_SessionPtr,
    ref.types.CString,
    TF_OutputPtr,
    voidPtr,
    ref.types.int32,
    TF_OutputPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_DeletePRunHandle: [ref.types.void, [
    ref.types.CString,
  ]],
  TF_NewDeprecatedSession: [TF_DeprecatedSession, [
    TF_SessionOptionsPtr,
    TF_StatusPtr,
  ]],
  TF_CloseDeprecatedSession: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    TF_StatusPtr,
  ]],
  TF_DeleteDeprecatedSession: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    TF_StatusPtr,
  ]],
  TF_Reset: [ref.types.void, [
    TF_SessionOptionsPtr,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_ExtendGraph: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_Run: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    TF_BufferPtr,
    voidPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    TF_BufferPtr,
    TF_StatusPtr,
  ]],
  TF_PRunSetup: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    voidPtr,
    TF_StatusPtr,
  ]],
  TF_PRun: [ref.types.void, [
    TF_DeprecatedSessionPtr,
    ref.types.CString,
    voidPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    voidPtr,
    ref.types.int32,
    voidPtr,
    ref.types.int32,
    TF_StatusPtr,
  ]],
  TF_LoadLibrary: [TF_Library, [
    ref.types.CString,
    TF_StatusPtr,
  ]],
  TF_GetOpList: [TF_Buffer, [
    TF_LibraryPtr,
  ]],
  TF_DeleteLibraryHandle: [ref.types.void, [
    TF_LibraryPtr,
  ]],
  TF_GetAllOpList: [TF_BufferPtr, [
  ]],
});

// Custom bindings
// Default destructor for Buffer-backed tensors. It's required by TF but a no-op since Buffers are GC'd.
exports.TF_Destructor = FFI.Callback('void', ['void*', 'size_t', 'void*'], function (data, len, arg) { });

// Throw an error if the status isn't TF_OK
exports.TF_CheckOK = function (status) {
  var code = exports.libtensorflow.TF_GetCode(status);
  if (code !== exports.CONSTANTS[''].TF_OK) {
    throw new Error(exports.libtensorflow.TF_Message(status));
  }
}

// TF_TensorData just returns a point to the data but the buffer isn't initialized to the long of the data for us. So we need to expand the buffer with reinterpret then set the correct type so that deref knows how to cast the buffer.
exports.TF_ReadTensorData = function (tensor, size, type) {
  var ptr = libtensorflow.TF_TensorData(tensor);
  ptr = ptr.reinterpret(size, 0);
  ptr.type = type;
  return ptr.deref();
}

module.exports = exports;
```

**Comment by jmanteigueiro** [comment]
Does everything else works with that part commented?

**Comment by basickarl** [comment]
@jmanteigueiro Indeed, nothing complains once I comment it.

**Comment by jmanteigueiro** [comment]
I'll bet on something related with the .so file, maybe that's not the name of the function in it.
