### ISSUE TITLE
Uncaught Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by beautycss** [node-ffi/node-ffi#408]
### Expected
Use modules "ffi" and "ref" in app to call dll.

### Problem
can't find the two node modules "ffi" and "ref" in app;
run ok in electron dev environment: modules installed and js can call dll succcess;

I don't know whether it's the problem of electron or ffi;

NodeJS: 8.3.0
Electron: 1.7.5
OS: Win 10

### I have tried
* electron-rebuild: success and completed
* copy node_modules folder into resources folder of the new app

### Error
```
Uncaught Error: %1 is not a valid Win32 application.
\\?\F:\project\out7\yle-win32-ia32\resources\node_modules\ffi\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (F:\project\out7\yle-win32-ia32\resources\node_modules\ffi\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (F:\project\out7\yle-win32-ia32\resources\node_modules\ffi\node_modules\ref\lib\ref.js:5:47)
```

**Comment by beautycss** [comment]
this issue could be closed.
electron packager should be arch=x64 instead of 32.

**Comment by junxion-io** [comment]
Do you remember what your fix for this was? I seem to be getting the same error. Here are my settings.

```
electron-builder -mwl --x64 --ia32
```
