### ISSUE TITLE
Dynamic Linking Error 193

### ISSUE THREAD

**Issue by AnaisSrg** [node-ffi/node-ffi#425]
Hi everybody,

I didn't find a solution for my problem in similar issues, so I post my problem :
I call a C++ library with node ffi like this :  

var library = new ffi.Library(__dirname +'./OpcUaWrapper_x64.dll', { 

And, when I launched Node Red, I obtain this error :
Error: Dynamic Linking Error: Win32 error 193

But I verified, I have dll, node-red, node ffi and my dll in 64bits version.

I found that, if I placed in my module directory, it works. So, I don't understand why it doesn't work when I placed elsewhere...

If you have any ideas for my problem, I take !

Thanks !

**Comment by stern0** [comment]
I have a similar problem, I have a ```.dylib``` file but when I load the library I get this error:

```
/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(����, 2): image not found
    at new DynamicLibrary (/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/node_modules/ffi/lib/library.js:45:12)
```

**Comment by hemavidal** [comment]
I had the same problem and i saw the function that i called didn't exists in DLL.
So, i fix the function name and ffi works fine.
The function 'sio_open ' bellow has a space in the end:
```javascript
const libm = ffi.Library(filePath, {
  'sio_open ': [ 'int', [ 'int' ] ]
})
```
I removed the space and works fine now:
```javascript
const libm = ffi.Library(filePath, {
  'sio_open': [ 'int', [ 'int' ] ]
})
```
It's strange! The error must generates other log instead of **Error: Dynamic Linking Error: Win32 error 193**.

**Comment by jackple** [comment]
@hemavidal Have you fixed this problem?

**Comment by hemavidal** [comment]
Yes!

**Comment by navono** [comment]
Maybe compile .cpp with x64 compiler will fix the 193 error.

**Comment by ghost** [comment]
I had the same problem. I use the dumpbin to check all dll resources... Get the 64x version... and nothing to now!! Someone know another manual to use ffi?

**Comment by SiJinmin** [comment]
project - property - configuration manager - x64

**Comment by yhongm** [comment]
> Maybe compile .cpp with x64 compiler would fix the `Error: Dynamic Linking Error: Win32 error 193`.

正解
