### ISSUE TITLE
Error while starting the Node Express Server :: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by goel-sunny** [node-ffi/node-ffi#442]
i am using Ref , ffi modules in my project . calling of 32 bit dll from the 64 bit os through ffi module.

i have build the native part of ffi and ref using node-gyp rebuild --arch=ia32 .

after building the native addons , when i start the server using node app.js on localhost :-

i get the following error :- 

Error: %1 is not a valid Win32 application.

\\?\C:\Users\Komal\Desktop\express\myapp\node_modules\ref\build\Release\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\Komal\Desktop\express\myapp\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\Komal\Desktop\express\myapp\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:570:32)
[nodemon] app crashed - waiting for file changes before starting...

if any one have idea related to this ,  pls reply .

**Comment by KriyenKP** [comment]
I seem to be having the same issue. Have you solved it?

**Comment by goel-sunny** [comment]
rebuild your native modules using the electron-rebuild from node-modules/.bin/electron-rebuild and pass the proper flag .

**Comment by KriyenKP** [comment]
Still having the same issue. I tried node-gyp --arch=ia32 on ffi and on ref.
Even when I don't load a DLL, i get this error. It crashes on 

`var ffi = require('ffi');`

**Comment by goel-sunny** [comment]
check your dll is architecture and the native module you are going to build are same i.e. x86 or ia32 .

sorry electron-rebuild is for electron based application , you are using the right tool i.e. node-gyp

**Comment by gzx-miller** [comment]
I have same issue, how to fix it?
