### ISSUE TITLE
cannot install ffi@2.2.0 on macOS

### ISSUE THREAD

**Issue by y-ich** [node-ffi/node-ffi#443]
I tried to install ffi@2.2.0 on macOS and failed.

My environment is,
macOS - 10.13.2
/usr/bin/cc - Apple LLVM version 9.0.0 (clang-900.0.39.2) 

Here is an output.

    iMac:npm yuji$ npm install ffi
    
    > ref@1.3.5 install /Users/yuji/Studies/JavaScript/node_modules/ref
    > node-gyp rebuild
    
      CXX(target) Release/obj.target/binding/src/binding.o
    ../src/binding.cc:643:8: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      Nan::ForceSet(target, Nan::New<v8::String>("endianness").ToLocalChecke...
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/binding.cc:644:8: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      Nan::ForceSet(target, Nan::New<v8::String>("NULL").ToLocalChecked(), W...
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    2 warnings generated.
      SOLINK_MODULE(target) Release/binding.node
    
    > ffi@2.2.0 install /Users/yuji/Studies/JavaScript/node_modules/ffi
    > node-gyp rebuild
    
      CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
      CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
      LIBTOOL-STATIC Release/libffi.a
      CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
    ../src/ffi.cc:58:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_OK);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:59:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_BAD_TYPEDEF);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:60:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_BAD_ABI);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:63:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_DEFAULT_ABI);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:64:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_FIRST_ABI);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:65:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_LAST_ABI);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:81:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_SYSV);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:83:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(FFI_UNIX64);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:88:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_LAZY);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:91:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_NOW);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:94:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_LOCAL);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:97:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_GLOBAL);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:100:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_NOLOAD);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:103:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_NODELETE);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:106:3: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      SET_ENUM_VALUE(RTLD_FIRST);
      ^
    ../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
      Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \
           ^
    ../../nan/nan_maybe_43_inl.h:116:1: note: 'ForceSet' has been explicitly marked
          deprecated here
    NAN_DEPRECATED inline Maybe<bool> ForceSet(
    ^
    ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/ffi.cc:111:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapP...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:111:100: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...*)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:114:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("RTLD_DEFAULT").ToLocalChecked(), Wr...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:114:106: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...*)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:117:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("RTLD_SELF").ToLocalChecked(), WrapP...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:117:100: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...*)RTLD_SELF), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:120:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("RTLD_MAIN_ONLY").ToLocalChecked(), ...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:120:110: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...*)RTLD_MAIN_ONLY), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:123:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("FFI_ARG_SIZE").ToLocalChecked(), Na...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:123:116: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...static_cast<PropertyAttribute>(ReadOnly|DontDelete));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:124:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("FFI_SARG_SIZE").ToLocalChecked(), N...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:124:118: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...static_cast<PropertyAttribute>(ReadOnly | DontDelete));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:125:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), N...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:125:118: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...static_cast<PropertyAttribute>(ReadOnly | DontDelete));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:126:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("FFI_CIF_SIZE").ToLocalChecked(), Na...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:126:116: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...static_cast<PropertyAttribute>(ReadOnly | DontDelete));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    ../src/ffi.cc:132:11: warning: 'ForceSet' is deprecated
          [-Wdeprecated-declarations]
      target->ForceSet(Nan::New<String>("HAS_OBJC").ToLocalChecked(), Nan::N...
              ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3114:3: note: 'ForceSet' has been
          explicitly marked deprecated here
      V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8config.h:321:29: note: expanded from
          macro 'V8_DEPRECATED'
      declarator __attribute__((deprecated))
                                ^
    ../src/ffi.cc:132:95: error: no viable conversion from 'v8::PropertyAttribute'
          to 'Local<v8::Value>'
      ...static_cast<PropertyAttribute>(ReadOnly | DontDelete));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit copy constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'const v8::Local<v8::Value> &' for 1st argument
    class Local {
          ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:197:7: note: candidate constructor
          (the implicit move constructor) not viable: no known conversion from
          'v8::PropertyAttribute' to 'v8::Local<v8::Value> &&' for 1st argument
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:201:13: note: candidate template
          ignored: could not match 'Local<type-parameter-0-0>' against
          'v8::PropertyAttribute'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:3116:51: note: passing argument to
          parameter 'value' here
                                         Local<Value> value,
                                                      ^
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:208:5: error: assigning to
          'v8::Context *' from incompatible type 'v8::String *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/yuji/.node-gyp/9.3.0/include/node/v8.h:162:39: note: expanded from macro
          'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                          ^~~~~~~~~~~~~~~~~~
    ../src/ffi.cc:111:20: note: in instantiation of function template specialization
          'v8::Local<v8::Context>::Local<v8::String>' requested here
      target->ForceSet(Nan::New<String>("RTLD_NEXT").ToLocalChecked(), WrapP...
                       ^
    24 warnings and 10 errors generated.
    make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
    gyp ERR! System Darwin 17.3.0
    gyp ERR! command "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/yuji/Studies/JavaScript/node_modules/ffi
    gyp ERR! node -v v9.3.0
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok 
    npm WARN enoent ENOENT: no such file or directory, open '/Users/yuji/Studies/JavaScript/package.json'
    npm WARN JavaScript No description
    npm WARN JavaScript No repository field.
    npm WARN JavaScript No README data
    npm WARN JavaScript No license field.
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ffi@2.2.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/yuji/.npm/_logs/2017-12-15T02_25_22_373Z-debug.log

**Comment by kjunichi** [comment]
Hi, y-ich

2.2.0 is not support node v9.x.

I guess that the patch was merged but some ci tests fail, this is the reason why new one hasn't been released yet.

For more detail info:

Support Node.js 9.x version #439

**Comment by owencm** [comment]
Switch to node@8 then try again, worked for me

**Comment by alexcastillo** [comment]
Same here, any updates?

**Comment by belloyang** [comment]
I got the same error with node v8.12.0 and v8.4.0 @owencm which version do u use exactly that works?

**Comment by kriss23** [comment]
Version 8.12.0 worked for me on MacOS Majave 10.14.1

Installed via:
`nvm install --lts 8`

**Comment by l0ca1** [comment]
i am fail with node v8.12.0

**Comment by guilhermeKodama** [comment]
I have the same issue:
```
npm ERR! ffi@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.3.0 install script.
```
Node - v8.12.0
OSX - 10.15
NPM - 6.4.1
