### ISSUE TITLE
Cannot Install with node 8.6.3

### ISSUE THREAD

**Issue by keyiis** [node-ffi/node-ffi#448]
I already install `node-gyp` and `windows-build-tools`,but still can't install ffi
```
D:\work\nodejs\demo>npm i ffi

> ref@1.3.5 install D:\work\nodejs\demo\node_modules\ref
> node-gyp rebuild


D:\work\nodejs\demo\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\work\nodejs
\demo\node_modules\ref\build\binding.vcxproj]
  d:\work\nodejs\demo\node_modules\nan\nan_maybe_43_inl.h(116): n
  ote: 参见“Nan::ForceSet”的声明
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': 被声明为已否决 [D:\work\nodejs
\demo\node_modules\ref\build\binding.vcxproj]
  d:\work\nodejs\demo\node_modules\nan\nan_maybe_43_inl.h(116): n
  ote: 参见“Nan::ForceSet”的声明
C:\Users\Administrator\.node-gyp\8.9.3\x64\node.lib : fatal error LNK1106: 文件 无效
或磁盘已满: 无法查找到 0x1F84E8 [D:\work\nodejs\demo\node_modules\ref\build
\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\work\nodejs\demo\node_modules\ref
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN test-dongle@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\work\nodejs\global_modules\cache\_logs\2018-01-24T04_39_58_642Z-debug.log
```
below is my npm config
```
D:\work\nodejs\demo>npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.com/"
scope = ""
user-agent = "npm/5.5.1 node/v8.9.3 win32 x64"

; userconfig C:\Users\Administrator\.npmrc
cache = "D:\\work\\nodejs\\global_modules\\cache"
msvs_version = "2015"
prefix = "D:\\work\\nodejs\\global_modules\\modules"
python = "C:\\Python27"
registry = "https://registry.npmjs.com/"

; globalconfig D:\work\nodejs\global_modules\modules\etc\npmrc
cache = "D:\\work\\nodejs\\global_modules\\cache"
msvs_version = "2015"
prefix = "D:\\work\\nodejs\\global_modules\\modules"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = D:\work\nodejs\demo
; HOME = C:\Users\Administrator
; "npm config ls -l" to show all defaults.
```

**Comment by scanhand** [comment]
i have same problem.

-------------------------------------------------------------------------------------
PS E:\work\DICOMViewer\electron\resources\app\JS> npm i -s ffi

E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
이 솔루션의 프로젝트를 한 번에 하나씩 빌드합니다. 병렬 빌드를 사용하려면 "/m" 스위치를 추가하 세요.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': deprecated로 선언되었습니다. [E:\work\DICOMVi
ewer\electron\resources\app\JS\node_modules\ref\build\binding.vcxproj]
  e:\work\dicomviewer\electron\resources\app\js\node_modules\nan\nan_maybe_43_inl.h(116): not
  e: 'Nan::ForceSet' 선언을 참조하십시오.
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': deprecated로 선언되었습니다. [E:\work\DICOMVi
ewer\electron\resources\app\JS\node_modules\ref\build\binding.vcxproj]
  e:\work\dicomviewer\electron\resources\app\js\node_modules\nan\nan_maybe_43_inl.h(116): not
  e: 'Nan::ForceSet' 선언을 참조하십시오.
     E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ref\build\Release\binding.lib
   라이브러리 및 E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ref\build\Release\bindi
  ng.exp 개체를 생성하고 있습니다.
  코드를 생성하고 있습니다.
  All 202 functions were compiled because no usable IPDB/IOBJ from previous compilation was f
  ound.
  코드를 생성했습니다.
  binding.vcxproj -> E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ref\build\Rel
  ease\\binding.node

E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
이 솔루션의 프로젝트를 한 번에 하나씩 빌드합니다. 병렬 빌드를 사용하려면 "/m" 스위치를 추가하 세요.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ffi\build\Release
  \\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
..\src\ffi.cc(111): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>
,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': 인수 3을(를) 'v8::PropertyAtt
ribute'에서 'v8::Local<v8::Value>'(으)로 변환할 수 없습니다. [E:\work\DICOMViewer\electron\resources\app\
JS\node_modules\ffi\build\ffi_bindings.vcxproj]
....

**Comment by scanhand** [comment]
i have same problem. my node version is 9.3.0.

--------
c:>node -v
v9.3.0

--------

$npm i -s ffi
...
if not defined npm_config_node_gyp (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\scanhand\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
...
 Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> E:\work\DICOMViewer\electron\resources\app\JS\node_modules\ffi\build\Release
  \\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
..\src\ffi.cc(111): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>
,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3
 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [E:\work\DICOMViewer\electron\resourc
es\app\JS\node_modules\ffi\build\ffi_bindings.vcxproj]
  ..\src\ffi.cc(111): note: No user-defined-conversion operator available that can perform th
  is conversion, or the operator cannot be called
...
