### ISSUE TITLE
Errors while installing on node v9.7.0

### ISSUE THREAD

**Issue by martynasS** [node-ffi/node-ffi#465]
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(111): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(111): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(114): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(114): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(123): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(123): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(124): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(124): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(125): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(125): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(126): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(126): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(132): error C2664: 'v8::Maybe<bool> v8::Ob
ject::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert
 argument 3 from 'v8::PropertyAttribute' to 'v8::Local<v8::Value>' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\no
de_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(132): note: No user-defined-conversion o
  perator available that can perform this conversion, or the operator cannot be called
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\callback_info.cc(63): warning C49
  96: 'Nan::Callback::Call': was declared deprecated

  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call'c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(64): warning C4996: 'Nan::ForceS
  et': was declared deprecated

  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\callback_info.cc(73): warning C4996: 'Nan::Callba
ck::Call': was declared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_binding
s.vcxproj]
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(65): warning C4996: 'Nan::ForceSet': was d
eclared deprecatedc:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan.h(1618): note: see declaration
of 'Nan::Callback::Call' [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]

  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\callback_info.cc(78): warning C4996: 'Nan::Callba
ck::Call': was declared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_binding
s.vcxproj]
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call'
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': was d
eclared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of '
  Nan::ForceSet'
c:\users\martynas\documents\projects\aura-sdk-js\node_modules\ffi\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call'
: was declared deprecated [C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi\build\ffi_bindings.vcxproj
]
  c:\users\martynas\documents\projects\aura-sdk-js\node_modules\nan\nan.h(1618): note: see declaration of 'Nan::Callbac
  k::Call'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Martynas\Documents\Projects\aura-sdk-js\node_modules\ffi
gyp ERR! node -v v9.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Martynas\Documents\Projects\aura-sdk-js\package.json'
npm WARN aura-sdk-js No description
npm WARN aura-sdk-js No repository field.
npm WARN aura-sdk-js No README data
npm WARN aura-sdk-js No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Martynas\AppData\Roaming\npm-cache\_logs\2018-03-29T16_04_50_396Z-debug.log
```
I'm getting this build error while installing. My node version is 9.7.0

**Comment by andreracz** [comment]
I've sucessfully compiled with Node 10.1.0 by using the source code from github. 
To do so, instead of `npm install ffi`
Use `npm install https://github.com/node-ffi/node-ffi.git `

**Comment by w01fgang** [comment]
@unbornchikken @TooTallNate please, can you publish the new version?

**Comment by oeN** [comment]
Installed from the repo on node `v10.4.1` everything worked fine, can the new version be published?

Thanks!

**Comment by w01fgang** [comment]
@unbornchikken @TooTallNate it works from the repo, but what about dependent packages?
Is it hard to publish a new version on npm? Do you need help to do it?

**Comment by unbornchikken** [comment]
Hi! LGTM, but I don't have publishing rights of the npm package.

**Comment by winrono** [comment]
Still doesn't work with simple "npm install ffi". However, works as expected using solution provided by @andreracz

**Comment by winrono** [comment]
@TooTallNate is it going to be fixed someday?

**Comment by uhhrace** [comment]
Solution provided by @andreracz works with Node v8.11.3, is there an eta for the release @TooTallNate ?

**Comment by andreieftimie** [comment]
What's the solution here?
Should the `node-ffi` project be published under a different name in `npm`, so the project can move forward?
