### ISSUE TITLE
use node-ffi make a mistake

### ISSUE THREAD

**Issue by liushaohua** [node-ffi/node-ffi#470]
Hello All,
I am having a electron project.
```
const ffi = require('ffi');
```
```
> electron main.js

App threw an error during load
Error: Module version mismatch. Expected 50, got 59.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/liushaohua/Documents/DATA/MeiShi_IM_electron/node_modules/.1.3.0@bindings/bindings.js:83:50)
```

My package.json dependencies look like this:
```
"dependencies": {
    "ffi": ">=2.2",
    "ref": ">=1.3"
 },
```
my node version is `v6.14.1`.

**Comment by pierreca** [comment]
I ran into this in the past and interpreted it to be when ffi is compiled against the wrong version of node/v8. cleaning up the node-modules folder and reinstalling fixed it for me. HTH

**Comment by TooTallNate** [comment]
Also be sure to have compiled the module using Electron's instructions about native modules: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
