### ISSUE TITLE
“node.h”: No such file or directory 

### ISSUE THREAD

**Issue by Ekko1995** [node-ffi/node-ffi#478]
vs2015
python 2.7.15
node 8.11.1

How could I fix this problem?
I had already install  vs2015、python step by step in accordance with the requirements of node-gyp environment.

H:\node>cnpm install -g ffi
Downloading ffi to H:\node\node_modules\ffi_tmp
Copying H:\node\node_modules\ffi_tmp\_ffi@2.2.0@ffi to H:\node\node_modules\ffi
Installing ffi's dependencies to H:\node\node_modules\ffi/node_modules
[1/5] nan@2 installed at node_modules\_nan@2.10.0@nan
[2/5] ref-struct@1 installed at node_modules\_ref-struct@1.1.0@ref-struct
[3/5] debug@2 installed at node_modules\_debug@2.6.9@debug
ref@1 found binding.gyp file, auto run "node-gyp rebuild"

H:\node\node_modules\ffi\node_modules\_ref@1.3.5@ref>node "H:\node\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
[4/5] bindings@~1.2.0 installed at node_modules\_bindings@1.2.1@bindings
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(5): fatal error C1083: 无法打开包括文件: “node.h”: No such file or directory [H:\node\node_modules\ffi\node_modules\_ref@1.3.5@ref\buil
d\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (H:\node\node_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "H:\\node\\node.exe" "H:\\node\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\node\node_modules\ffi\node_modules\_ref@1.3.5@ref

**Comment by Ekko1995** [comment]
I solved this problem. Python2.7 does not support Chinese path name . When I use npm install ffi --devdir=$no_chinese_path ，the installation went smoothly.
