### ISSUE TITLE
npm install ffi failing

### ISSUE THREAD

**Issue by maneyko** [node-ffi/node-ffi#484]
<img width="416" alt="screen shot 2018-07-04 at 4 04 35 pm" src="https://user-images.githubusercontent.com/14032795/42294078-0aff444e-7fa4-11e8-8516-4fa35057ea4c.png">

I ran `npm install ffi` and the build failed on my macbook.

Setup:
MBP w/ MacOS 10.13.4
Hardware: 11,1

Log:
```
> ffi@2.2.0 install /Users/Maciej/projects/tester/node_modules/ffi
> node-gyp rebuild

  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/libffi.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Maciej/projects/tester/node_modules/ffi
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN tester No description
npm WARN tester No repository field.
npm WARN tester No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Maciej/.npm/_logs/2018-07-04T21_04_08_132Z-debug.log
```

Thanks.

**Comment by windwaterbo** [comment]
I have the same problem 👀

**Comment by reebr** [comment]
Same problem here.
Is this project still maintained? 🤔

**Comment by yangypDeveloper** [comment]
The same problem 🤔

**Comment by aquark** [comment]
The problem appears to be that `gyp-mac-tool` uses `#!/usr/bin/env python` so it uses the default python and doesn't respect the `python=python2.7` setting in `.npmrc` which is normally sufficient for `node-gyp`. I was able to work around it using `pyenv global 2.7.8 3.6.7` to make `python` resolve to 2.7 by default. The fix should be for `gyp-mac-tool` to respect `.npmrc`.

**Comment by terrybondy** [comment]
Running `pyenv local system` once in the build directory worked for me.

**Comment by guilhermeKodama** [comment]
I am having the same issue and `node-gyp` is using python 2.7. I can't run `yarn add ffi`
```
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
```

**Comment by tonytbui** [comment]
@aquark I have the same problem above. Could you clarify a bit on what commands to run to implement the fixes you suggested? Thanks!
