### ISSUE TITLE
Kneeling for solution, NPM installation failed

### ISSUE THREAD

**Issue by yfjl** [node-ffi/node-ffi#485]
C:\dll\electron-quick-start-master\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\dll\electron-quick-start-master\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
..\src\ffi.cc(111): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(114): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(123): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(124): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(125): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(126): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(132): error C2039: “ForceSet”: 不是“v8::Object”的成员 [C:\dll\electron-quick-start-master\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
  c:\users\yangfeng\.node-gyp\10.4.0\include\node\v8.h(3155): note: 参见“v8::Object”的声明
..\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\callback_info.cc(63): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [C:\dll\electron-quick-start-master\node_mod
ules\ffi\build\ffi_bindings.vcxproj]
  C:\dll\electron-quick-start-master\node_modules\nan\nan.h(1618): note: 参见“Nan::Callback::Call”的声明
..\src\ffi.cc(64): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\callback_info.cc(73): warning C4996: 'Nan::Callback::Call': 被声明为已否决..\src\ffi.cc(65): warning C4996: 'Nan::Force
Set': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\ffi_bindings.vcxproj]

  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明C:\dll\electro
  n-quick-start-master\node_modules\nan\nan.h(1618): note: 参见“Nan::Callback::Call”的声明

..\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
..\src\callback_info.cc(78): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [C:\dll\electron-quick-start-master\node_mod
ules\ffi\build\ffi_bindings.vcxproj]
  C:\dll\electron-quick-start-master\node_modules\nan\nan.h(1618): note: 参见“Nan::Callback::Call”的声明c:\dll\electron-quic
  k-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明

..\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\build\f
fi_bindings.vcxproj]
  c:\dll\electron-quick-start-master\node_modules\nan\nan_maybe_43_inl.h(130): note: 参见“Nan::ForceSet”的声明
..\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call': 被声明为已否决 [C:\dll\electron-quick-start-master\node_modules\ffi\
build\ffi_bindings.vcxproj]
  C:\dll\electron-quick-start-master\node_modules\nan\nan.h(1618): note: 参见“Nan::Callback::Call”的声明
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dll\electron-quick-start-master\node_modules\ffi
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yangfeng\AppData\Roaming\npm-cache\_logs\2018-07-05T15_18_34_530Z-debug.log

**Comment by Liupeng8** [comment]
在项目目录下运行 "./node_modules/.bin/electron-rebuild" "./node_modules/ffi"  可解决你的问题，npm run dev 可正常运行，但是npm run build不行，暂时还没解决。

**Comment by Liupeng8** [comment]
补充一下，我用的electron-vue框架

**Comment by Liupeng8** [comment]
@githoniel Thank you, the problem has been solved. After installing NPM dependency, build operation is first implemented, and it can enter the development mode normally.
