### ISSUE TITLE
ffi@2.2.0, Windows 10, node 7.10.1: node-gyp rebuild fails with MSB3686

### ISSUE THREAD

**Issue by Anrock** [node-ffi/node-ffi#503]
Here is `npm i` log:
```
npm i
npm WARN npm npm does not support Node.js v7.10.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11.
npm WARN npm You can find the latest version at https://nodejs.org/

> ffi@2.2.0 install C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi
> node-gyp rebuild


C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Users\vladislav.shtepin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vladislav.shtepin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB3686: U
nable to create Xaml task.  Compilation failed.  \r [C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\
build\deps\libffi\ffi.vcxproj]
C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB3686: S
ource file 'C:\Windows\TEMP\ordt2cwm.0.cs' could not be found\r [C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_
modules\ffi\build\deps\libffi\ffi.vcxproj]
C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB3686:
[C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\deps\libffi\ffi.vcxproj]
C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB4036: T
he "assembler" task was not found. Check the following: 1.) The name of the task in the project file is the same as the
 name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3
.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Prog
ram Files (x86)\MSBuild\14.0\bin" directory. [C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi\build\d
eps\libffi\ffi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\vladislav.shtepin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vladislav.shtepin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vladislav.shtepin\Desktop\electron-dapp\node_modules\ffi
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vladislav.shtepin\AppData\Roaming\npm-cache\_logs\2018-09-12T12_44_29_861Z-debug.log
```

Any help? Can't find anything relevant in google.

**Comment by Puddinglord** [comment]
Is there a reason you are using node 7? I know for a fact that ffi works with node 9.11 which is what we are using for our project. Node 7 isn't even officially supported by Node anymore so it would be wise to upgrade.

**Comment by Anrock** [comment]
@Puddinglord electron 1.7 is based on node 7, so i have to compile native modules with it, otherwise ABI mismatches.

**Comment by Puddinglord** [comment]
Ahh ok then, that's a good reason!

**Comment by waitingsong** [comment]
change deps
```
    "ffi": "^2.2.0"
```

to 

```
    "ffi": "git+https://github.com/node-ffi/node-ffi.git"
```

It worsk under node v10.9.0 64bit

**Comment by Anrock** [comment]
I've already reinstalled windows and problem is gone.

**Comment by moialbla** [comment]
@waitingsong´s solutions for windows 10 works fine, thanks!
