### ISSUE TITLE
The callback function causes the process to crash

### ISSUE THREAD

**Issue by git-duanjl** [node-ffi/node-ffi#518]
....... DLL is : 
       // callback function
       typedef void ( *CallbackFun)(Status* status);
      
      //  init function 
       int init(IN CallbackFun callbackFun);

     // Status is struct
     typedef struct tagStatusStruct
     {
	   int mode;				
	   int left;		
	   int right;		
	   unsigned char imageData[20];
	   int reservedInfo[10]; 
       }Status, *pStatus;

......... ffi is : 
  const ffi = require('ffi');
  const ref = require('ref');
  const refStruct = require('ref-struct');
  const refArray = require('ref-array');

let Status = refStruct({
    'mode': 'int', 
    'left': 'int',
    'right': 'int', 
    'imageData': refArray('char',20),
    'reservedInfo': refArray('int',10) 
});

let libM = ffi.Library('sdk/E30/IKUSBSDK.dll',{
    'init': ['int', ['pointer']], 
});

let statusCB = ffi.Callback('void',[ref.refType(Status)] , (data) => {
    console.log(`Buffer deref : ${ref.get()}`)
});

let f = libM.init(statusCB);
 console.log('Init REL : ' , f);

...... result is : 
Init REL :  0
Buffer deref : [object Object]
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! electron-object@1.0.0 start: `electron .`
npm ERR! Exit status 3221225477
npm ERR! 
npm ERR! Failed at the electron-object@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\win-10\AppData\Roaming\npm-cache\_logs\2018-11-24T07_48_22_362Z-debug.log

Process finished with exit code -1073741819 (0xC0000005)

........... Excuse me, what is the situation?

**Comment by crazyeruca** [comment]
me too, helpinginging....

**Comment by RoeelCohen** [comment]
Same here.
I tried using ffi with c++ and c# code, at first everything worked fine including callbacks.
Problem started when the dll I'm loading is connected to another process I'm receiving an error when trying to invoke a function with a callback.


Here's my code:

```
const e = ffi.Library('C:\\Path\\to\\my.dll', {
  Setup: ['void', []],
  Initialize: ['bool', ['pointer']],
  ExecuteFunction: ['string', ['string', 'string', 'string']]
});

const cbRef = ffi.Callback('void', ['string', 'string'], function(callbackName, jsonRes) {
  console.log(callbackName, ' called with: ', jsonRes);
});

engine.Setup();
engine.Initialize(cbRef);


process.on('exit', function() {
  cbRef;
});

engine.ExecuteFunction('data','moreData', "{\"enable\":true}");

```

Here's the stack:
```
18 verbose stack Error: ffic@1.0.0 start: `node index.js`
18 verbose stack Exit status 3221225501
18 verbose stack     at EventEmitter.<anonymous> (C:\...\v10.0.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
18 verbose stack     at EventEmitter.emit (events.js:182:13)
18 verbose stack     at ChildProcess.<anonymous> (C:\...\v10.0.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:182:13)
18 verbose stack     at maybeClose (internal/child_process.js:947:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
19 verbose pkgid ffic@1.0.0
20 verbose cwd C:\Repos\ffic
21 verbose Windows_NT 10.0.17134
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 verbose node v10.0.0
24 verbose npm  v5.6.0
25 error code ELIFECYCLE
26 error errno 3221225501
27 error ffic@1.0.0 start: `node index.js`
27 error Exit status 3221225501
```

The crash is starting immediately when I try to invoke `engine.ExecuteFunction`, the function won't stop the debugger on visual studio for the dll side, it seems like node is crashing immediately.

**Comment by fengxiaochuang** [comment]
我也是, 但是希望我的回复还不算晚对于其他获得相同错误的人来说.
总的来说, 是因为垃圾回收机制导致的.
你需要把回调函数绑定到一个不会被垃圾回收的对象上, 比如引用的指针(this).

Me too, but hope my reply is not too late for others who get the same error.
In general, it is caused by the garbage collection mechanism.
You need to bind the callback function to an object that will not be garbage collected, such as the referenced pointer (this).

before:
```javascript
    init(callback) {
        const sessionStartCallback = ffi.Callback('void', ['int', pEventInfo, ref.types.void],
            (event) => {
                debug(`hci voicewake callback msg :${event}`)
                callback(event)
            }
        );
       ...
    }
 ```

after:
```javascript
    init(context, callback) {
        context.sessionStartCallback = ffi.Callback('void', ['int', pEventInfo, ref.types.void],
            (event) => {
                debug(`hci voicewake callback msg :${event}`)
                callback(event)
            }
        );
    }
    ...
```
and use it:
```javascript
xxxx.init(this, (event)=>{
})
```
