### ISSUE TITLE
yarn add ffi error

### ISSUE THREAD

**Issue by hengkx** [node-ffi/node-ffi#520]
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\GitHub\qzd\qzd-desktop-app\node_modules\ref
```
```
node v10.14.1
npm 6.4.1
windows 10 1803 OS build 1134.407
yarn 1.12.3
VS 2017
node-gyp 3.8.0
```

![image](https://user-images.githubusercontent.com/8358236/49267168-1b96b980-f494-11e8-9461-e23779c53c34.png)
![image](https://user-images.githubusercontent.com/8358236/49267184-32d5a700-f494-11e8-86b4-b702c1ef5606.png)

![image](https://user-images.githubusercontent.com/8358236/49267251-7b8d6000-f494-11e8-8e31-da22ba210d5b.png)
![image](https://user-images.githubusercontent.com/8358236/49267257-821bd780-f494-11e8-827b-ea9e9020a6e9.png)

**Comment by chengdonglin** [comment]
Do you have deal with this problem? I have meet the same question?
