### ISSUE TITLE
about -v2.3.0

### ISSUE THREAD

**Issue by ainama** [node-ffi/node-ffi#522]
```
C:\Users\frog\work\TaskGoNative>npm run rebuild

> taskgonative@0.1.0 rebuild C:\Users\frog\work\TaskGoNative
> electron-rebuild.cmd

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\callback_info.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\callback_info.cc)
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\ffi.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\ffi.cc)
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(63): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(73): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(78): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\threaded_callback_invokation.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\threaded_callback_invokation.cc)
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(64): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(65): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(111): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(114): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(123): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(124): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(125): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(126): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(132): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\frog\work\TaskGoNative\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\frog\\work\\TaskGoNative\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.12" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\frog\work\TaskGoNative\node_modules\ffi
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\callback_info.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\callback_info.cc)
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\ffi.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\ffi.cc)
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(63): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(73): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\ffi\src\callback_info.cc(78): warning C4996: 'Nan::Callback::Call': ��� ���Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1081): error C2660: ��v8::String::WriteUtf8��: ���������� 5 ������ (����Դ�ļ� ..\src\threaded_callback_invokation.cc) [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\.electron-gyp\.node-gyp\iojs-3.0.12\deps\v8\include\v8.h(2590): note: �μ���v8::String::WriteUtf8� ������� (����Դ�ļ� ..\src\threaded_callback_invokation.cc)
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(64): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(65): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(111): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(114): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(123): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(124): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(125): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(126): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(132): warning C4996: 'Nan::ForceSet': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan_maybe_43_inl.h(130): note: �μ���Nan::ForceSet������� �
c:\users\frog\work\taskgonative\node_modules\ffi\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call': ������Ϊ�ѷ�� [C:\Users\frog\work\TaskGoNative\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\frog\work\taskgonative\node_modules\nan\nan.h(1658): note: �μ���Nan::Callback::Call��������
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\frog\work\TaskGoNative\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\frog\\work\\TaskGoNative\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=3.0.12" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\frog\work\TaskGoNative\node_modules\ffi
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\frog\work\TaskGoNative\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Users\frog\work\TaskGoNative\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.next (C:\Users\frog\work\TaskGoNative\node_modules\rxjs\Subscriber.js:189:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! taskgonative@0.1.0 rebuild: `electron-rebuild.cmd`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the taskgonative@0.1.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frog\AppData\Roaming\npm-cache\_logs\2018-12-17T10_34_21_572Z-debug.log
```

**Comment by TooTallNate** [comment]
Try upgrading your version of Node.js. v9.11.1 is not a stable release.

**Comment by githoniel** [comment]
see https://github.com/node-ffi/node-ffi/pull/523

```
npm i nan@2.10.0
```
will help in node v10

**Comment by iamdaning** [comment]
@TooTallNate Thank you for your answer.
