### ISSUE TITLE
How to load a dynamic library that needs another library?

### ISSUE THREAD

**Issue by jonathan-roy** [node-ffi/node-ffi#525]
Hi,

I am new to Node FFI and more generally to native addons. I need to wrap a dynamic library on MacOS (let's call it libA), which needs to load another dynamic library (libB). This is my project structure:
- `build/`
    - `libA.dylib`
    - `libB.dylib`
- `lib/`
    - `a.js`

`lib/a.js` is where I create my wrapper:
```js
// [...]
const addon = ffi.Library("./build/libA.dylib", {
	// [...]
});
// [...]
```

Now when I want to test this, from the project root folder: `node ./lib/a.js`. FFI seems to be able to load `libA`, but then `libB` is not loaded:
```
Error: Dynamic Linking Error: dlopen(./build/libA.dylib, 2): Library not loaded: @rpath/libB.dylib
  Referenced from: /Users/jroy/Workspace/test-node-ffi/build/libA.dylib
  Reason: image not found
    at new DynamicLibrary (/Users/jroy/Workspace/test-node-ffi/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/jroy/Workspace/test-node-ffi/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/Users/jroy/Workspace/test-node-ffi/lib/a.js:31:19)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

How am I supposed to handle this? Do I need to copy `libB.dylib` somewhere else (I already tried to copy it in `lib` and in the project root folder without success)?

**Comment by manuxdjent** [comment]
I have the same problem.
I tried to put the dependencies in my System32 folder and it doesn't work every time.

**Comment by i-tengfei** [comment]
same problem, any help?

**Comment by manuxdjent** [comment]
In my case the solution was fixing the DLL path using 'path.join'.

`const dllFunctions = ffi.Library(path.join(static__, myDll.dll), {
	// some code
});`

**Comment by NelsonFrancisco** [comment]
I have the same problem.
Setting process.env.PATH to the dependency's folder does nothing.

**Comment by siuying** [comment]
I cannot find a solution of this problem. 

The best workaround I managed to found is add a `postinstall` step to the package:

```
{
  "postinstall" : "ln -s $INIT_CWD/node_modules/your-npm/lib/libname.so $INIT_CWD/libname.so"
}
```

On npm install, the postinstall script will soft link the library to project root path, which solve the issue for me.

**Comment by MeloHo** [comment]
I have similar use cases as yours. But I do have control over `libA.dylib`. So I set the `rpath` of `libA.dylib` by this line in its CMake file and it works:
`set_target_properties(${PROJECT_NAME} PROPERTIES INSTALL_RPATH "@loader_path")`
It basically added the `loader_path` to `rpath` of the target, thus `libA.dylib` will look into its loader_path to find libB.dylib.
