### ISSUE TITLE
fficonfig.h: No such file or directory (Armbian/Ubuntu)

### ISSUE THREAD

**Issue by janispritzkau** [node-ffi/node-ffi#533]
I can't install a package that uses `node-ffi` on Armbian. I installed the `libffi6` and `libffi-dev` package.

I'm running the latest Node version 11.

```
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:0:
../deps/libffi/include/ffi_common.h:17:10: fatal error: fficonfig.h: No such file or directory
 #include <fficonfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by janispritzkau** [comment]
When I don't have these packages installed I get this error:

```
make: Entering directory '/home/XXX/.npm-packages/lib/node_modules/XXX/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
../deps/libffi/src/prep_cif.c:26:10: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
          ^~~~~~~
compilation terminated.
```

**Comment by robertsLando** [comment]
I have this problem too, any news?

**Comment by robertsLando** [comment]
I think it is related to #393

**Comment by olof-nord** [comment]
I run into the same issue when trying to install [Signal-Desktop](https://github.com/signalapp/Signal-Desktop/issues/3410) on my PinePhone running mobian. Are there any known solutions?

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/mobian/git/Signal-Desktop/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
In file included from ../deps/libffi/src/prep_cif.c:27:
../deps/libffi/include/ffi_common.h:17:10: fatal error: fficonfig.h: No such file or directory
   17 | #include <fficonfig.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [deps/libffi/ffi.target.mk:127: Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mobian/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.7-pinephone
gyp ERR! command "/home/mobian/.nvm/versions/node/v12.13.0/bin/node" "/home/mobian/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
make: Leaving directory '/home/mobian/git/Signal-Desktop/node_modules/ffi-napi/build'
gyp ERR! cwd /home/mobian/git/Signal-Desktop/node_modules/ffi-napi
```

```
Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.7-pinephone
Architecture: arm64
```

**Comment by sangshuduo** [comment]
same here with Ubuntu 20.10 on RPi 4 Model B.

**Comment by WieeRd** [comment]
same here with Ubuntu 20.04 LTS on RPi 4 Model B.

**Comment by andyedwardsibm** [comment]
same here with Red Hat 8 on ppc64le
