### ISSUE TITLE
Should I use x32 dll in x32 system and x64 dll in x64 system ?

### ISSUE THREAD

**Issue by nbhaohao** [node-ffi/node-ffi#537]
My OS is Windows7x64, and I want to build a electron app.
I use ffi, When I use the x32 dll file, the error is show. 
```
  // li_pos_dll.dll is a x32 dll file.
  const User32$32 = ffi.Library(`${__dirname}/lf_pos_dll.dll`, {});
  console.log('call x32 result', User32$32);
```
```
// error
(node:3156) UnhandledPromiseRejectionWarning: Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (D:\zzh\workspace\lemon\chen-demo\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (D:\zzh\workspace\lemon\chen-demo\node_modules\ffi\lib\library.js:45:12)
    at App.Library (D:\zzh\workspace\lemon\chen-demo\app/main.dev.js:69:25)
    at App.emit (events.js:187:15)
(node:3156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by reje
cting a promise which was not handled with .catch(). (rejection id: 1)
(node:3156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.

```
When I use x64 dll file, It works, for example:
```
  const User32$64 = ffi.Library(`user32`, {
    GetWindowLongPtrW: ['int', ['int', 'int']]
  });
  log.warn('call x64 result', User32$64.GetWindowLongPtrW);
```

So, If anyone can help and tell me, that the dll version must match the OS running version ?

I try to config my `.npmrc` to match the dll file. if the dll file is x32, I change the vars to 'ia32',  but it is not work.
```
registry=https://registry.npm.taobao.org/
target=3.0.10
arch=x64  // I try change this to 'ia32'
target_arch=x64  // I try change this to 'ia32'
disturl=https://atom.io/download/electron
runtime=electron
build_from_source=true
python=python2.7
msvs_version=2017
```

**Comment by nbhaohao** [comment]
I realize that x32 can use in x64 and x32

**Comment by yft** [comment]
how do you resolve this problem?

**Comment by ghost** [comment]
You can favor using the `x86` 32bit by default, 
and use https://nodejs.org/api/os.html#os_os_arch to figure out if the CPU is capable of 64bit calculations, in which case you can use, instead, the x64 version of the DLL file.
