### ISSUE TITLE
Unsupport for node 12.x

### ISSUE THREAD

**Issue by liudonghua123** [node-ffi/node-ffi#545]
I updated my node to `12.0.0`, then it did not work, the full output of `npm i` is belows.

```shell
D:\code\ynu\wexond>npm i

> ref@1.3.5 install D:\code\ynu\wexond\node_modules\ffi\node_modules\ref
> node-gyp rebuild


D:\code\ynu\wexond\node_modules\ffi\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\Liu.D.H\AppData\Roaming\nvm\v12.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Liu.D.H\AppData\Roaming\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(222): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [D:\code\ynu\wexond\node_modules\
ffi\node_modules\ref\build\binding.vcxproj]
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(253): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [D:\code\ynu\wexond\node_modules\ffi\nod
e_modules\ref\build\binding.vcxproj]
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(360): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8
::Local<v8::Value>' to 'const v8::String::Utf8Value &' [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
  d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(360): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(360): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be
  called
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(447): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8
::Local<v8::Value>' to 'const v8::String::Utf8Value &' [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
  d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(447): note: Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value'
  d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(447): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be
  called
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(521): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [D:\code\ynu\wexond\node_modules\ffi\nod
e_modules\ref\build\binding.vcxproj]
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(550): error C2660: 'v8::Value::Uint32Value': function does not take 0 arguments [D:\code\ynu\wexond\node_modules\ffi\nod
e_modules\ref\build\binding.vcxproj]
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(582): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(583): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(584): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(585): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(586): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(587): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(588): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(589): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(590): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(591): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(593): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(594): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(595): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(596): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(597): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(598): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(599): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(600): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(601): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(602): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(603): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(604): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(605): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(606): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(608): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(615): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(616): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(617): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(618): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(619): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(620): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(621): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(622): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(623): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(624): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(625): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(626): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(627): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(628): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(629): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(630): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(631): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(632): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(633): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(634): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(635): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(636): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(637): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(638): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(641): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(642): warning C4996: 'v8::Object::Set': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\bu
ild\binding.vcxproj]
  c:\users\liu.d.h\.node-gyp\12.0.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\buil
d\binding.vcxproj]
  d:\code\ynu\wexond\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
d:\code\ynu\wexond\node_modules\ffi\node_modules\ref\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [D:\code\ynu\wexond\node_modules\ffi\node_modules\ref\buil
d\binding.vcxproj]
  d:\code\ynu\wexond\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Liu.D.H\AppData\Roaming\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Liu.D.H\\AppData\\Roaming\\nvm\\v12.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\code\ynu\wexond\node_modules\ffi\node_modules\ref
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN wexond@2.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Liu.D.H\AppData\Roaming\npm-cache\_logs\2019-04-29T01_40_31_724Z-debug.log

D:\code\ynu\wexond>
```

**Comment by liudonghua123** [comment]
I just found there was a pr (https://github.com/node-ffi/node-ffi/pull/544) already.

**Comment by sanchezpablo** [comment]
This happened to me using electron 5.0, which has Node 12... any progress on this? Thanks!

**Comment by ranihorev** [comment]
There is a fork that supports Node 12:
https://github.com/lxe/node-ffi/tree/node-12

We also published it to npm:
https://www.npmjs.com/package/@saleae/ffi

**Comment by roy2651** [comment]
> There is a fork that supports Node 12:
> https://github.com/lxe/node-ffi/tree/node-12
> 
> We also published it to npm:
> https://www.npmjs.com/package/@saleae/ffi

hi, @ranihorev great work first all,
but I have some problems to use it 
now I'm working on nodejs bridge objective-c with this repo [NodObjC](https://github.com/TooTallNate/NodObjC),but this repo is not support node 12 and electron5, our project is using this two version(node12，electron5）but I don't work it out
my steps as following:
1. I forked https://github.com/TooTallNate/NodObjC 
2. I modify package.json, and replace 
    "ffi": "github:lxe/node-ffi#node-12",
    "ref": "github:lxe/ref#node-12",
    "ref-struct": "github:lxe/ref-struct#node-12"
3. npm install 

when I npm install it turns errors
but this does not work
please help me

**Comment by stiv-yakovenko** [comment]
I was able to use it: 

**npm install @saleae/ffi**

```
var ffi = require("@saleae/ffi");

var libm = ffi.Library("libm", {
    ceil: ["double", ["double"]]
});
console.log(libm.ceil(1.5)); // 2
```

**Comment by gino8080** [comment]
hot to get typescript definitions for @saleae/ffi and @saleae/ref?

**Comment by lionel1702** [comment]
https://github.com/microsoft/node-pty/issues/319

**Comment by alxndrsn** [comment]
@ranihorev thanks for providing node 12 support - your fork at https://www.npmjs.com/package/@saleae/ffi seems to work great.

A quick question though - the published version on npm is `3.0.2`, but the version number in the repo at https://www.npmjs.com/package/@saleae/ffi is `3.0.0`, there are no 3.x tags at https://github.com/lxe/node-ffi/tags, and there don't seem to be any branches in that repo which add to `3.0.0`.  Is the source code for version `3.0.2` available?

**Comment by rtf-const** [comment]
@saleae/ffi seems not to work in node 14. Yo can use node-ffi-napi as an alternative
