### ISSUE TITLE
Error: Dynamic Symbol Retrieval Error: Win32 error 127 when binding to ActiveX control functions 

### ISSUE THREAD

**Issue by LitchGZ** [node-ffi/node-ffi#548]
I want call the "put_Server" function in ActiveX control mstscax.dll

```javascript
var ffi = require('.ffi')
var mstsc = ffi.Library('./mstscax.dll', {
  'put_Server': [ 'void', [ 'string' ] ]
})
```
And I got the below error
```
Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (e:\zhoulf\node-ffi\lib\dynamic_library.js:112:11)
    at e:\zhoulf\node-ffi\lib\library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (e:\zhoulf\node-ffi\lib\library.js:47:28)
    at Object.<anonymous> (e:\zhoulf\node-ffi\example\factorial\factorial.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Waiting for the debugger to disconnect...
Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (e:\zhoulf\node-ffi\lib\dynamic_library.js:112:11)
    at e:\zhoulf\node-ffi\lib\library.js:50:19
    at Array.forEach (<anonymous>)
    at Object.Library (e:\zhoulf\node-ffi\lib\library.js:47:28)
    at Object.<anonymous> (e:\zhoulf\node-ffi\example\factorial\factorial.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

My environment is : 
```
E:\zhoulf\node-ffi>node -v
v10.15.3

E:\zhoulf\node-ffi>npm -v
6.9.0

OS version: Windows 10

mstscax.dll: ActiveX control 
```

How to solve this error? Does node-ffi support ActiveX control on Windows OS?

**Comment by 406087475** [comment]
you should use path.join(__dirname, './mstscax.dll')

**Comment by raviSussol** [comment]
@LitchGZ Did you resolve the issue by now. I'm having the same issue on my mac and have been searched almost all options in the internet to resolve this issue but still facing the same error. I have my files like these:
add.go

```
package main

import "C"

func Add(x, y int) int {
	return x + y
}

func main() {}

```

and goNodeTest.js

```
const { resolve } = require('path');
const ffi = require('ffi-napi');
const ref = require('ref-napi');
const sharedGoLib = resolve(__dirname, './add');

const int = ref.types.int;
const nodeGo = ffi.Library(sharedGoLib, {
  Add: [ int, [ int, int ] ],
});

console.log(nodeGo.Add(2, 4));

```
Can anyone tell me whats missing on those 2 files above or have gone wrong? Any help would be appreciated. Thanks.
