### ISSUE TITLE
can't rebuild ffi package in window 10,more error details

### ISSUE THREAD

**Issue by LuoRiWuSheng** [node-ffi/node-ffi#549]
**Basic environment**

- node: 12.0.0
- python 2.7.15
- electron 5.0.0
- node-gyp   global installation  

（english:）Here are my steps.（chinese: 以下是我的操作步骤）
1、 ` npm install node-gyp -g`

2、`npm install --global --production windows-build-tools `
3、`npm config set msvs_version 2017`
4、in window 10   , Configuration python 2.7 system environment
5、 `npm config set python C:\softForDIY\python-2.7.15\python.exe`
6、 `mkdir test-electron`
7、`cd test-electron`
8、`npm init -y & npm install ffi electron --save`
9、`npm install electron-rebuild -D`
10、`.\node_modules\.bin\electron-rebuild .\node_modules\ffi\`

but, No matter what I did, the compilation failed.

`gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.0.0 | win32 | x64
gyp info spawn C:\Users\Administrator\.windows-build-tools\python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\test-ffi\\node-ffi\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\12.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\12.0.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.node-gyp\\12.0.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\test-ffi\\node-ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\test-ffi\\node-ffi\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test-ffi\node-ffi
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok`

Please give me some guidance.

**Comment by weue** [comment]
I have encountered the same problem.
`Node-gyp rebuild --target=4.0.0 --arch=x64 --dist-url=https://atom.io/download/electron`
This has been successful, so I suspect that the above version of electron5.0 is not available.
