### ISSUE TITLE
ENOENT: no such file or directory, open 'libipps.so'

### ISSUE THREAD

**Issue by tzvc** [node-ffi/node-ffi#578]
Hi there,

I'm trying to run a node js app using node-ffi on a Ubuntu docker and I get this error

```
{ Error: ENOENT: no such file or directory, open 'libipps.so'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at new DynamicLibrary (/usr/src/app/node_modules/ffi/lib/dynamic_library.js:67:21)
    at Object.Library (/usr/src/app/node_modules/ffi/lib/library.js:45:12)
    at rPPGPipeline.initialize (/usr/src/app/src/lib/rPPG_pipeline.js:58:24)
    at Session._callee$ (/usr/src/app/src/lib/session.js:13:20)
    at tryCatch (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/src/app/src/lib/session.js:9:191) errno: -2, syscall: 'open', code: 'ENOENT', path: 'libipps.so' }
```

What am I missing here>?

**Comment by exonent** [comment]
Probably your path is wrong, try to paste your relative path :)
