### ISSUE TITLE
Cannot install on nodejs v12.16.2, node-gyp v5.1.0, Ubuntu 18.4 LTS.

### ISSUE THREAD

**Issue by LeonidRosin** [node-ffi/node-ffi#588]
I think the case is in the **nodejs** version (v12.16.2). Nodejs 8.10.0 **npm install ffi** runs OK.
> The current version is tested to run on node v0.6, v0.8, v0.9 and v0.10.

```
binding.target.mk:111: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/lr/works/skm-srv/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/snap/node/2632/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/snap/node/2632/bin/node" "/snap/node/2632/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lr/works/skm-srv/node_modules/ref
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lr/.npm/_logs/2020-04-19T15_22_50_976Z-debug.log

```

**Comment by LeonidRosin** [comment]
I have solution.

Node.js is moving to NAPI so everyone and everything is moving to -napi to avoid compatibility issues.
We use **[ref-napi](https://www.npmjs.com/package/ref-napi)** instead of **ref** and **[ffi-napi](https://www.npmjs.com/package/ffi-napi)** instead of **ffi**

**Thank you all, issue is closed!**  ;-)
