### ISSUE TITLE
FFI on iOS?

### ISSUE THREAD

**Issue by exonent** [node-ffi/node-ffi#591]
Hi, 
I want to use **FFI** in **iOS** as I do in **windows 10 (UWP)**. 
I'm trying to use with [Node-Mobile Cordova](https://github.com/janeasystems/nodejs-mobile-cordova), but I get an error in **XCode** saying:

> platform log:-->  ios
> module.js:529
>     throw err;
>     ^
> 
> Error: Cannot find module 'ffi'
>    at Module._resolveFilename (module.js:529:5)
>    at Module._load (module.js:476:5)
>    at Module.prototype.require (module.js:568:3)
>    at require (internal/module.js:11:7)
>    at Anonymous function (/Users/userName/Library/Developer/CoreSimulator/Devices/BCB5D5BB-47A3-4E3D-B264-450AFE33234B/data/Containers/Bundle/Application/9F12F94D-3EDF-45D5-AFFB-0B7DBD2271EB/ADS appname.app/www/nodejs-project/main.js:12:1)
>    at Module.prototype._compile (module.js:624:5)
>    at Module._extensions[.js] (module.js:635:3)
>    at Module.prototype.load (module.js:545:3)
>    at tryModuleLoad (module.js:508:5)
>    at Module._load (module.js:500:3)

**My steps are:** 

1. `npm install ffi` (Project folder)
2. `ionic build ios`
3. Open **XCode** with the project
4. `Run(Play)` in **XCode**
5. **Error above**

Someone tried to build FFI on iOS? If you did, please tell me the secret ;) Thx!

**Comment by nicholaswhittle** [comment]
Did you find a solution to this?
