### ISSUE TITLE
Dynamic Linking Error 193 with x64 Node

### ISSUE THREAD

**Issue by jmw992** [node-ffi/node-ffi#606]
Working on some common code and I am getting the following error calling a small dll for licensing where as my colleagues are not.

```
library  ./resources/extras/licensing/licensing.dll
Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (C:\Users\DummyUser\AppPath\app\node_modules\ffi-napi\lib\/dynamic_library.js:74:11)
    at Library (C:\Users\DummyUser\AppPath\app\node_modules\ffi-napi\lib\/library.js:47:14)
    at App.createWindow (C:\Users\DummyUser\AppPath\app\/main.dev.ts:131:20)
    at App.emit (events.js:215:7)
```

The calling code is the following

```
import { screen, app, BrowserWindow, ipcMain } from 'electron';
import { autoUpdater } from 'electron-updater';
import { Library } from 'ffi-napi';

const libPath = `./resources/extras/licensing/licensing.dll`;
const libWeb = Library(libPath, {
  validate: ['int32', ['int32']]
});
```

The dll should be a 32 for reasons related to the licensing code, but still I've tried building it as x64, and running it but I get the same issue.  This appears to be similar to the unresolved issue #425 .

From googling it appears similar to the following link, but the fix was recommended to upgrade the dll to x64, which doesn't work
https://stackoverflow.com/questions/53051284/error-dynamic-linking-error-win32-error-193-while-binding-to-eztwain3-dll-libr

Because it is working on other's machines we are thinking it may have something to do with the build environment.  I have tried re-installing npm & windows build tools.

Versions of tools I'm using are below, appreciate any experience or insight someone may have.

- Windows 10 (64)
- node version 6.14.8
- ffi-napi version 3.0.1

**Comment by jmw992** [comment]
There appeared to be an error in my Windows environment and the issue was fixed by a full windows reset.  Nuclear option, but effective.
