### ISSUE TITLE
electron中使用node-ffi问题

### ISSUE THREAD

**Issue by javabitar** [node-ffi/node-ffi#609]
electron中使用node-ffi问题：
1、这个项目太老了。NODE_MODULE_VERSION只支持到64,超过编译就报错，不管是node-gyp或者electron rebuild。
    也就是说只要nodejs超过v12，则node-ffi编译就会报错，提示各种函数类型参数等不正确，只能node<v12来编译。。。
2、node：https://nodejs.org/zh-cn/download/releases/
    electron:https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json
  大家伙可以看上边连接来对应两者的NODE_MODULE_VERSION,版本不**相等**则无法在electron调用node-ffi。
3、c模式的dll可以使用node-ffi，缺点nodejs不支持v12及以上，停更了。
4、c++模式的dll，有高人提供了ffi-napi且支持到nodejs v12.，但v12版本也很低(对应electron v5 现在稳定是v9)
5、我需要在electron中调用c dll，我该怎么办？？？

**Comment by Z1hgq** [comment]
node v10完全够用呀

**Comment by guoxiao0521** [comment]
谢谢老哥！

**Comment by javabitar** [comment]
ffi-napi现在支持到nodejs 14了：直接使用ffi-napi 可以调用c++，而c++兼容c，即cor c++dll都可以用。
ffi-napi Add support for Node.js 14, drop for < 10

**Comment by dbssAlan** [comment]
> ffi-napi现在支持到nodejs 14了：直接使用ffi-napi 可以调用c++，而c++兼容c，即cor c++dll都可以用。 ffi-napi Add support for Node.js 14, drop for < 10

您好，请问现在支持node16、node18、node20吗？

**Comment by liudonghua123** [comment]
I tried a simple demo with ffi-napi. And it works for node 18, 20.

```
D:\code\node\playground>node -v
v18.14.2

D:\code\node\playground>cat ffi_example1.js
const ffi = require('ffi-napi');

const libm = ffi.Library('./libopenlibm.dll', {
  'sin': [ 'double', [ 'double' ] ],
  'cos': [ 'double', [ 'double' ] ],
});

console.info(`sin(0): ${libm.sin(0)}`);
console.info(`cos(0): ${libm.cos(0)}`);

D:\code\node\playground>node ffi_example1.js
sin(0): 0
cos(0): 1

D:\code\node\playground>nvm use 20.3.0
Now using node v20.3.0 (64-bit)

D:\code\node\playground>node -v
v20.3.0

D:\code\node\playground>node ffi_example1.js
sin(0): 0
cos(0): 1

D:\code\node\playground>
```

Due to the lack of libm on windows, I tried to use https://github.com/JuliaMath/openlibm instead.

[ffi_example1.zip](https://github.com/node-ffi/node-ffi/files/12424881/ffi_example1.zip)

**Comment by liudonghua123** [comment]
And I also notice for the standard `atoi` function in the default library. I need to change `null` to `` `${process.platform == 'win32' ? 'msvcrt' : 'libc'}${ffi.LIB_EXT}` ``, or I will get `Uncaught Error: Dynamic Symbol Retrieval Error: Win32 error 127` errors.

```
> ffi.Library(null, {'atoi': [ 'int', [ 'string' ] ]})
Uncaught Error: Dynamic Symbol Retrieval Error: Win32 error 127
    at DynamicLibrary.get (D:\code\node\playground\node_modules\ffi-napi\lib\dynamic_library.js:113:11)
    at D:\code\node\playground\node_modules\ffi-napi\lib\library.js:55:21
    at Array.forEach (<anonymous>)
    at Object.Library (D:\code\node\playground\node_modules\ffi-napi\lib\library.js:52:28)
> ffi.Library('msvcrt.dll',{'atoi': [ 'int', [ 'string' ] ]})
{ atoi: [Function: proxy] { async: [Function (anonymous)] } }
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>

D:\code\node\playground>cat ffi_example1.js
const ffi = require('ffi-napi');

var current = ffi.Library(`${process.platform == 'win32' ? 'msvcrt' : 'libc'}${ffi.LIB_EXT}`, {
  'atoi': [ 'int', [ 'string' ] ]
});
console.info(current.atoi('1234')); // 1234

D:\code\node\playground>node ffi_example1.js
1234

D:\code\node\playground>
```

**Comment by liudonghua123** [comment]
> And I also notice for the standard `atoi` function in the default library. I need to change `null` to `` `${process.platform == 'win32' ? 'msvcrt' : 'libc'}${ffi.LIB_EXT}` ``, or I will get `Uncaught Error: Dynamic Symbol Retrieval Error: Win32 error 127` errors.
> 
> ```
> > ffi.Library(null, {'atoi': [ 'int', [ 'string' ] ]})
> Uncaught Error: Dynamic Symbol Retrieval Error: Win32 error 127
>     at DynamicLibrary.get (D:\code\node\playground\node_modules\ffi-napi\lib\dynamic_library.js:113:11)
>     at D:\code\node\playground\node_modules\ffi-napi\lib\library.js:55:21
>     at Array.forEach (<anonymous>)
>     at Object.Library (D:\code\node\playground\node_modules\ffi-napi\lib\library.js:52:28)
> > ffi.Library('msvcrt.dll',{'atoi': [ 'int', [ 'string' ] ]})
> { atoi: [Function: proxy] { async: [Function (anonymous)] } }
> >
> (To exit, press Ctrl+C again or Ctrl+D or type .exit)
> >
> 
> D:\code\node\playground>cat ffi_example1.js
> const ffi = require('ffi-napi');
> 
> var current = ffi.Library(`${process.platform == 'win32' ? 'msvcrt' : 'libc'}${ffi.LIB_EXT}`, {
>   'atoi': [ 'int', [ 'string' ] ]
> });
> console.info(current.atoi('1234')); // 1234
> 
> D:\code\node\playground>node ffi_example1.js
> 1234
> 
> D:\code\node\playground>
> ```

I took a deep look at the code. If I pass `null` as the first argument to `ffi.Library`, the final call is `GetModuleHandle(NULL, ...)`. And according to the [docs](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlea#parameters) (`If this parameter is NULL, GetModuleHandle returns a handle to the file used to create the calling process (.exe file).)`, `atoi` which in the `msvcrt.dll` is not loaded, so I got `Uncaught Error: Dynamic Symbol Retrieval Error: Win32 error 127`. 


And the common functions like `sin`, `cos`, `atoi` is in msvcrt.dll.

![image](https://github.com/node-ffi/node-ffi/assets/2276718/b78cd492-574c-4535-996d-1695162acecc)
