### ISSUE TITLE
question:TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument

### ISSUE THREAD

**Issue by johnzhu12** [node-ffi/node-ffi#611]
node version: v8.11.1
node-gyp: v7.0.0
Mac osx: 10.13.6 

```js
'use strict'
var ffi = require('ffi');
console.log(__dirname)
// void pre_init(pp* param)
var libm = ffi.Library(__dirname + '/lib/libpre', {
    'pre_init': ['void', ['pointer']]
});
function test() {
    let param
    libm.pre_init(param);
};
test()
```
```c
void pre_init(pp* param){
    int ret = mclBn_init(MCL_BN254, MCLBN_COMPILED_TIME_VAR);
    if (ret != 0) {
        printf("err ret=%d\n", ret);
	}
    mclBnG1_hashAndMapTo(&param->g1, "g1", 2);
    mclBnG2_hashAndMapTo(&param->g2, "g2", 2);
    mclBn_pairing(&param->e, &param->g1, &param->g2);
}
```
libpre is a .dylib file。
error message:
/Users/miya/Desktop/node-ffi
/Users/miya/Desktop/node-ffi/node_modules/ffi/lib/_foreign_function.js:55
      throw e
      ^

TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
    at Object.writePointer (/Users/miya/Desktop/node-ffi/node_modules/ref/lib/ref.js:747:11)
    at Object.set (/Users/miya/Desktop/node-ffi/node_modules/ref/lib/ref.js:489:13)
    at Object.alloc (/Users/miya/Desktop/node-ffi/node_modules/ref/lib/ref.js:521:13)
    at Object.proxy [as pre_init] (/Users/miya/Desktop/node-ffi/node_modules/ffi/lib/_foreign_function.js:50:22)
    at test (/Users/miya/Desktop/node-ffi/index.js:10:10)
    at Object.<anonymous> (/Users/miya/Desktop/node-ffi/index.js:12:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by ganeshrvel** [comment]
How did you fix this? what was the issue?

**Comment by johnzhu12** [comment]
@ganeshrvel 
we changed all the c functions to accept string input or string pointer and output strings, which is easy to handle  in ffi
